### PR TITLE
Add missing typescript type definitions

### PR DESCRIPTION
**Pull request by jaypea**
Adds missing type definitions on FixtureFN and TestFN for 
 - disablePageCaching
 - disablePageReloads

### CODE REVIEW

**Comment by jaypea** [comment]
@testcafe-build-bot retest

**Comment by AndreyBelym** [comment]
Thank you for your contribution! However, `disablePageReloads` is not ready for production and won't you mind if I remove it from your commit? Also, we need to reference the described method in [test/server/data/test-suites/typescript-defs/structure.ts](https://github.com/DevExpress/testcafe/blob/master/test/server/data/test-suites/typescript-defs/structure.ts) to cover it by autotests.

**Comment by jaypea** [comment]
Well, `disablePageReloads` is in the Code and working within its boundaries. Why shouldn't I as a typescript developer not be allowed to use it whereas javascript users are able to?
If testcafe would be written in typescript, this interface would be complete and working, right?

**Comment by AndreyBelym** [comment]
Well, it makes sense. But we should at least add a note that this feature is experimental and may be removed in the future TestCafe versions and mark it as `@private`.

**Comment by AndreyBelym** [comment]
NOTE: Since JSDoc doesn't have any modifiers like `@experimental`, `@preview` and so on, I thought that using `@private` that this method isn't meant for a public usage could be a good idea. But my colleague convinced me that we shouldn't use this tag. I've edited the original comment, but if you were fast and managed to read the first version: please do not add the `@private` tag.

**Comment by AndreyBelym** [comment]
@VasilyStrelyaev, could you please take a look at that?

**Pull request merged**
