### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by inikulin**
\cc @AlexanderMoskovkin

### CODE REVIEW

**Comment by inikulin** [comment]
Please, do not merge yet, there may be hammerhead update.

**Comment by AndreyBelym** [comment]
Please be careful when publishing if you are using `node>=6.0.0` && `npm<3.10.1`: https://github.com/npm/npm/releases/tag/v3.10.1

**Comment by inikulin** [comment]
@AndreyBelym Yeah, I know

**Comment by AlexanderMoskovkin** [comment]
closed in favor of #634

**Pull request closed without merging**
