### PR TITLE
Configuration file fixes 2 (from Vasily)

### PR DESCRIPTION
**Pull request by miherlosev**
@VasilyStrelyaev @AndreyBelym

### CODE REVIEW

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
FPR

**Comment by VasilyStrelyaev** [comment]
One thing though - now the parameter that specifies the output file in the config is called `outStream`, just as in JS API.

When I look at the discussion in the chat, I see you've suggested a better version - `file` or `fileName`.

`outStream` is good in API because you can pass a Stream object, but in config it's just a name.

Can we rename it to `fileName` or `file` in the config and leave it as `outStream` in JS API?

**Comment by miherlosev** [comment]
@VasilyStrelyaev 

> Can we rename it to fileName or file in the config and leave it as outStream in JS API?

I will do it in a separate PR.

**Pull request merged**
