### PR TITLE
Update testcafe-legacy-api version

### PR DESCRIPTION
**Pull request by Farfurix**
https://github.com/DevExpress/testcafe-legacy-api/pull/40
https://github.com/DevExpress/testcafe-hammerhead/issues/1651
https://github.com/DevExpress/testcafe-hammerhead/pull/1685

### CODE REVIEW

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by AndreyBelym** [comment]
@testcafe-build-bot  retest

**Comment by AndreyBelym** [comment]
@testcafe-build-bot retest

**Comment by AndreyBelym** [comment]
@testcafe-build-bot retest

**Comment by AndreyBelym** [comment]
Looks like there is a strange bug in Travis CI API: https://github.com/travis-ci/travis-ci/issues/10043

**Pull request closed without merging**
