### PR TITLE
Fixed client UI styles - attribute "float" protected (closes #341)

### LINKED ISSUE #341: Incorrect progress bar filling while uploading a file through non-existing element
When we try to upload a file using a non-existent element, the progress bar doesn’t fill up while waiting for the element to appear.
[Screencast](http://screencast.com/t/MjQvIFzo)

### PR DESCRIPTION
**Pull request by georgiy-abbasov**
\cc @AlexanderMoskovkin, @inikulin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
Why do you do this just for `.progress-panel.content` ? We can add `float: none;` to generic reset rule as was discussed [here](https://github.com/DevExpress/testcafe/issues/341#issuecomment-182410431)

**Comment by georgiy-abbasov** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by georgiy-abbasov** [comment]
ping @inikulin

**Comment by inikulin** [comment]
lgtm

**Pull request merged**
