### PR TITLE
Implement beforeEach/afterEach (closes #262)

### LINKED ISSUE #262: APIv2: Implement `beforeEach`, `afterEach`
Test cases:

| beforeEach | test | afterEach |
|----------|----|---------|
|    fail    | skip |    skip   |
|     run    | fail |    run    |
|     run    |  run |    fail |

- Should run `beforeEach` and `afterEach` for all tests in fixture

### PR DESCRIPTION
**Pull request by inikulin**
\cc @AlexanderMoskovkin @helen-dikareva @AndreyBelym

### CODE REVIEW

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
Seems like my changes to driver part which we've introduced with @AlexanderMoskovkin caused errors on Travis. The funny part is that it works just fine for me locally on Win machine. I doubt it something platform specifing. More likely it's a timing issue. @AlexanderMoskovkin any ideas?

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
I was able to localize the issue. IE11 hangs on uncaught error test.

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
Ok, I give up trying to fix js-error test hang up in context of this PR. We need to create separate issue and WIP PR with IE logging enabled to figure out the cause. This issue is not caused by this PR anyway.

FPR (https://github.com/DevExpress/testcafe/pull/457#issuecomment-211549607 - successful test run).
\cc @AlexanderMoskovkin @helen-dikareva @AndreyBelym

**Comment by AlexanderMoskovkin** [comment]
> We need to create separate issue

#460

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
lgtm

**Comment by AndreyBelym** [comment]
lgtm

**Pull request merged**
