### PR TITLE
Use V8 flag filters only in CLI. Helps avoid confusion when bin/testcafe.js is used for debugging from IDE

### PR DESCRIPTION
**Pull request by inikulin**
\cc @helen-dikareva @churkin @VasilyStrelyaev

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
@testcafe-build-bot \retest

**Comment by churkin** [comment]
@testcafe-build-bot /retest

**Comment by churkin** [comment]
@testcafe-build-bot /retest

**Comment by churkin** [comment]
@testcafe-build-bot /retest

**Pull request merged**
