### PR TITLE
add: not terminating process on one connection

### PR DESCRIPTION
**Pull request by yashLadha**
## Purpose
_Describe the problem you want to address or the feature you want to implement._
When there is an error in one of the browser-connection due to any error
reason, the complete process is closed because the error event promise
is resolved and thus disposing of assets gets started.

## Approach
_Describe how your changes address the issue or implement the desired functionality in as much detail as possible._

What actually should be done is perform the cleanup process when the
error is being emitted from all the connection and then emit the browerset
error and do not persuade the cleanup on the pending tasks. Logic for
this would be similar to follows.

## References
_Provide a link to the existing issue(s), if any._

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

### CODE REVIEW

**Comment by AndreyBelym** [comment]
Thank you for your contribution. I need to solve some other tasks before I can review this PR. Thank you for your patience.

**Comment by yashLadha** [comment]
@AndreyBelym Can you please re-review?

**Comment by yashLadha** [comment]
Hi @AndreyBelym any updates on this?

**Comment by AlexKamaev** [comment]
Hello. I examined your code, and I have some questions regarding it.


Could you please describe in detail why you don't wish to stop the process?


Let's assume that we have a series of tests. We run them in `chrome`, `firefox` and `ie`. The first test hangs in `chrome`. What should happen in `firefox` and `ie`? Should further tests continue in `firefox` and `ie`? We think that it's better to stop test execution because even if further tests pass in `ie` and `firefox`, we cannot mark them as `passed` because they were not executed in `chrome`.


Thus, we think that if we execute a test in multiple browsers, it should pass in all of them. If the test fails at least in one browser, this means that it does not pass.

**Comment by yashLadha** [comment]
@AlexKamaev Sorry for the late reply.

When the user wants to run on different browsers, the intention of the user is very much clear that they want to know the behavior of their site on different browsers. It might be that their site does not function properly on one browser and works on others, this information needs to be conveyed to the user. They will be able to use the information that your tests failed on chrome and worked on others, rather then your tests failed. Ideally, when there is an error on one connection, all the connections that share the same job-id should only be closed and other browsers should be running.

**Comment by AlexKamaev** [comment]
We discussed the issue with the team and concluded that the current behavior is correct. When we run tests in multiple browsers, we expect that tests should pass in every browser. We stop test execution after any browser hangs to decrease the time of the test task. This way, TestCafe users will get results immediately after errors. Otherwise, a user can get failed test results with a huge delay.
In the case when a user needs to test a browser separately, we would suggest splitting the CI task into multiple parts: one task for IE, one for Chrome, etc.

**Pull request closed without merging**
