### PR TITLE
Update hammerhead, bump version (close #1502)

### LINKED ISSUE #1502: No authenthication on a SPA with User Role
Not sure if this a bug, missing features or just my mistake but I can't get authenticated on a SPA with testcafe user roles.

I have build a (Polymer) SPA which uses a Drupal 7 backend,
The login takes place on a normal webpage on the Drupal(/user/login) server before the SPA get's started. After logon you can go to a URL-path (on the same domain) which points to the index.html which kickstarts the SPA and downloads the other files.  From the SPA the ajax-requests are made with "withCredentials" so that cookies (on the domain) are send with the request so we have an authenticated session. 

I am using testcafe with user roles which allows me to logon on the Drupal site and do some things on the  website being logged in.  When I "navigateTo" the URL-path which start de SPA download the SPA is started just fine within the proxy, but there is no session-cookie being forwarded with the ajax-calls.
I am not sure how I can test this any further (with t.debug() you cannot see any cookies).

Some code example:
const dirkUser = Role('http://test.dirk.e-wise.com/user/login', async t => {
    await t
        .typeText('#edit-name', 'dirk')
        .typeText('#edit-pass', 'PASSWORD')
        .click('#edit-submit');
});

test('Logging in', async t => {
  await t
    .useRole(dirkUser)
    .navigateTo('http://test.dirk.e-wise.com/app/lesson/1766/page/1')
    .debug()
    .expect(p.nextButton.exists).ok("No next button present")
    .click(p.nextButton);
 ....

Software:
Windows 10
Testcafe 0,15,0
NodeJS 7.6.0

I cannot provide URL for external testing because the application is not a public server yet, but I hope the given information is sufficient.

### PR DESCRIPTION
**Pull request by miherlosev**
@AlexanderMoskovkin @AndreyBelym

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
FPR

**Pull request merged**
