### PR TITLE
update hammerhead

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@LavrovArtem The `Native dialogs handling Errors during dialogs handling Should pass if the expected beforeUnload dialog appears after an action:` test fails several times. Please check it locally

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Pull request merged**
