### PR TITLE
Should ensure AsyncEventEmitter from additional event subscriptions (closes #4725)

### LINKED ISSUE #4725: `testRunController` emits the `test-run-start` event twice
```JS
testRunController.on('test-run-start', async () => {
    await this.emit('test-run-start', testRunController.testRun);
});
```

### PR DESCRIPTION
**Pull request by AlexKamaev**
Accidentally I duplicated the assign to the `test-run-start` event. Test will prevent this

### CODE REVIEW

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Comment by AlexKamaev** [comment]
the tests on Travis failed because of Chrome Update, not because of this PR

**Comment by AndreyBelym** [comment]
Yep, two tests failed due to now deprecated Shadow DOM in tests not related to this PR. Consider it GTM.

**Pull request merged**
