### PR TITLE
Remove related source code from inIFrame errors (closes #255)

### LINKED ISSUE #255: TestCafe server throws an exception if inIFrame target is not found
By some reason when client raises `emptyIFrameArgument` error it doesn't set `relatedSourceCode` property. Server throws an exception in function `getStepCode`, and hangs until browser is disconnected by heartbeat timeout.

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @AlexanderMoskovkin @helen-dikareva

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
Let's remove `relatedSourceCode` from [here](https://github.com/DevExpress/testcafe/blob/master/test/server/error-formatter-test.js#L357) because it's not true in this case

**Comment by AndreyBelym** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by helen-dikareva** [comment]
lgtm

**Pull request merged**
