### PR TITLE
Add file name to path argument for takeScreenshot action (close #687)

### LINKED ISSUE #687: Add file name to path argument for takeScreenshot action

### PR DESCRIPTION
**Pull request by helen-dikareva**
/cc @inikulin @AlexanderMoskovkin

### CODE REVIEW

**Comment by inikulin** [comment]
@helen-dikareva iframe test issue should be fixed by #686

**Comment by helen-dikareva** [comment]
Yep. I fixed it in https://github.com/DevExpress/testcafe/pull/675, but forget here

**Comment by inikulin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm but rebase required

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
