### PR TITLE
Get rid of 'isInputWithoutSelectionPropertiesInFirefox' (closes #379)

### LINKED ISSUE #379: Get rid of 'isInputWithoutSelectionPropertiesInFirefox'
We don't need this workaround, because [the related bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1003741) was fixed in Firefox 31. The method was removed in `testcafe-hammerhead` - https://github.com/helen-dikareva/testcafe-hammerhead/commit/68efea1ed3718a3e9a7adb3bc20f63b88cdc9cc6, but it's still used in `testcafe` code. That causes tests to fail: https://travis-ci.org/testcafe-build-bot/testcafe/jobs/112611017

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @inikulin @AlexanderMoskovkin @helen-dikareva

### CODE REVIEW

**Comment by inikulin** [comment]
I don't get it. How happened that hammerhead update broke the build?

**Comment by AndreyBelym** [comment]
There was a commit in`testcafe-hammerhead` on February 24 - https://github.com/DevExpress/testcafe-hammerhead/commit/68efea1ed3718a3e9a7adb3bc20f63b88cdc9cc6, that removed method `isInputWithoutSelectionPropertiesInFirefox` from `domUtils`. Unfortunately, the metod is still used in our `master` code in `key-press-simulator` and `type` automation - [here](https://github.com/DevExpress/testcafe/blob/master/src/client/runner/automation/playback/press/key-press-simulator.js#L36), [here](https://github.com/DevExpress/testcafe/blob/master/src/client/runner/automation/playback/type-char.js#L146), and [here](https://github.com/DevExpress/testcafe/blob/master/src/client/runner/automation/playback/type.js#L58). Plus in QUnit automation regression test - [here](https://github.com/DevExpress/testcafe/blob/master/test/client/fixtures/runner/automation/regression-test.js#L129). 

The method was a workaround for a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1003741) was appearing in Firefox 30 and below, so presumably it's safe to get rid of it.

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
> The method was a workaround for a bug was appearing in Firefox 30 and below, so presumably it's safe to get rid of it.

I understand. But I'm wondering how it's happened that we've introduced breaking change in HH and decided to publish it without major version bump, screwing the whole CI.
\cc @churkin

**Comment by helen-dikareva** [comment]
Changes are OK. But these tests make me sick, I was sure that thay are stable. Did you make rebase before making PR?

**Comment by churkin** [comment]
@inikulin @AndreyBelym Guys, this is my fault. I did not notice breaking change. I will update the hammerhead to v.7.0.0

**Comment by AndreyBelym** [comment]
It's based on top of `master`: [master tree](https://github.com/DevExpress/testcafe/commits/master), [PR tree](https://github.com/AndreyBelym/testcafe/commits/fa41d2039dac9bbb5f486282d6b6660c3854fbcc). Test results looks very suspicious BTW.

**Comment by churkin** [comment]
I will unpublish v6.0.1 from the npm

**Comment by AndreyBelym** [comment]
IMHO we also need to unpublish `@6.0.1`: [npm unpublish](https://docs.npmjs.com/cli/unpublish)

**Comment by churkin** [comment]
@AndreyBelym I'll take the testcafe upgrade to the new version of hammerhead

**Comment by AndreyBelym** [comment]
Ookay, just found an awesome link for this case : [checking out pull requests locally](https://help.github.com/articles/checking-out-pull-requests-locally/):smile:

**Comment by churkin** [comment]
> I will unpublish v6.0.1 from the npm

done

**Comment by churkin** [comment]
@helen-dikareva Tests that fell after @AndreyBelym fix just unstable?

**Comment by helen-dikareva** [comment]
I think test's behavior is not connected to PR so they still unstable. I'll try to fix it later in  https://github.com/DevExpress/testcafe/pull/376

**Comment by churkin** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

**Comment by churkin** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
Closing the PR, all changes will be integrated in type automation refactoring by @helen-dikareva.

**Pull request closed without merging**
