### PR TITLE
Disable strict mode for Babel transform (closes #258)

### LINKED ISSUE #258: Blacklist 'useStrict' in Babel
Strict mode disallows usage of `callee.caller`. So if a function traverses call stack with `callee.caller`, and TestCafe functions are strict-mode functions, an exception will be thrown. Unfortunately, we have  that nasty kind of a function in DevExpress ASP.Net controls, so we need to disable strict mode in Babel transform options.

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @AlexanderMoskovkin @helen-dikareva

### CODE REVIEW

**Comment by inikulin** [comment]
It needs regression test
\r-

**Comment by AndreyBelym** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Comment by helen-dikareva** [comment]
@VasilyStrelyaev please check test name.
I think we should add issue ID to test name.

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by helen-dikareva** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
