### PR TITLE
[docs] Added my puppeteer-chromium browser provider

### PR DESCRIPTION
**Pull request by stefanschenk**

### CODE REVIEW

**Comment by AndreyBelym** [comment]
Thank you for your contribution. I think we can add your browser provider to the list.

However, there is a thing that I find hard to understand. Could you please give some background on why you had to implement a Puppeteer integration? 

Recent TestCafe versions use DevTools for everything except page automation as much as Puppeteer. The only missing feature is downloading and installing browsers automatically. Is it really a killer feature or is Puppeteer better at something that we already have (screenshots, resizing, etc.)?

**Comment by AndreyBelym** [comment]
Also, @dahu33, won't you mind if we add your https://github.com/curvegrid/testcafe-browser-provider-puppeteer-core to our list? Your plugin looks quite useful and I expect it to be appreciated by the TestCafe community.

**Comment by stefanschenk** [comment]
> Thank you for your contribution. I think we can add your browser provider to the list.
> 
> However, there is a thing that I find hard to understand. Could you please give some background on why you had to implement a Puppeteer integration?

For now the puppeteer provider has no other means than to download and start the browser. 

By using this provider I'm not obligated to install the correct browser version on every system the tests are run on, be it a developer machine or ci machine. Instead the correct version is automatically installed in the node_modules folder when puppeteer itself is installed.

So thats the usecase for now. I have to look if other puppeteer specific features could be used and if that is necessary.

**Comment by dahu33** [comment]
> Also, @dahu33, won't you mind if we add your https://github.com/curvegrid/testcafe-browser-provider-puppeteer-core to our list? Your plugin looks quite useful and I expect it to be appreciated by the TestCafe community.

Please go ahead, we would be very happy to have our plugin in the list!

**Comment by dahu33** [comment]
@stefanschenk out of curiosity, what the difference between the already existing `testcafe-browser-provider-puppeteer` and your implementation `testcafe-browser-provider-puppeteer-chromium`? I couldn't figure it out by reading the README.

**Comment by stefanschenk** [comment]
@dahu33 for now, the biggest difference is that you can provide a chromium conf js file to overwrite defaults set in the provider. The plan is to tag the provider for different chrome/chromium revisions (for now chrome 77 and 78 are tagged). 
And the browser is by default started maximized with some logic to size the viewport correctly to display the testcafe debug bar on the correct position.

**Comment by AndreyBelym** [comment]
The test fails due to a broken link to the Jenkins docs in a completely different article. It was already fixed in the `master`.

**Pull request merged**
