### PR TITLE
Docs - Add a gulp task to publish the website

### LINKED ISSUE #277: Need the publish task for docs
Use `gulp-gh-pages` for that. Prompt before publishing.
Do when the docs are ready and it's safe to try it (there is an option for dry run in `gulp-gh-pages` - but do you trust it?).

### PR DESCRIPTION
**Pull request by VasilyStrelyaev**
fixes #277 
\cc @DevExpress/testcafe-docs

### CODE REVIEW

**Comment by inikulin** [comment]
lgtm

**Comment by kirovboris** [comment]
lgtm

**Comment by MargaritaLoseva** [comment]
lgtm

**Comment by VasilyStrelyaev** [comment]
@testcafe-build-bot  \retest

**Comment by AlexanderMoskovkin** [comment]
server tests are failed (rebase required)

**Comment by VasilyStrelyaev** [comment]
done

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
