### PR TITLE
Adding bitbucket pipelines sample for firefox

### PR DESCRIPTION
**Pull request by adityai**
## Purpose
The example for running test cafe on bitbucket cloud is outdated. The image circleci/node:10.14-browsers is outdated and does not work for the latest version of testcafe. 

## Approach
CircleCI has a newer version of node container images hosted as cimg/node, for the latest versions of node that is compatible with the latest version of testcafe. The image 'cimg/node:current-browsers' has the latest version of node installed in it. I was expecting browsers to be already installed in it but it was missing the browsers. Installing chrome using wget and apt-get did not quite work out and other dependencies may be required. If I figure it out, I will submit a separate PR for updating the chrome example. Installing firefox using wget was a lot more straightforward. So, I created a copy of the chrome example, edited it for running the tests using firefox and edited bitbucket-pipelines.yml to install firefox before running the tests.

## References
[cimg/node:current-browsers] https://hub.docker.com/layers/cimg/node/current-browsers/images/sha256-c250426a248f85446bd7639658ae30375b3c72481daa9744b242c054de11897f?context=explore

## Pre-Merge TODO
- [ ] Recommended Tests
- [ ] 1. Create a bitbucket repo with the content of examples/running-tests-in-firefox-using-bitbucket-pipelines-ci
- [ ] 2. Enable pipelines in the Bitbucket repo pipeline settings
- [ ] 3. Run the pipeline
- [ ] Make sure that existing tests do not fail

### CODE REVIEW

**Comment by adityai** [comment]
I don't understand what this means in the list of steps that showed up on the PR. Is this something I need to do?

Request Deployment / authenticate (pull_request_target) Waiting

**Comment by PavelMor25** [comment]
Hello @adityai,

Thank you for your pull request.

The `Request Deployment / authenticate (pull_request_target)` requires approval to run the workflow, so there's nothing further needed from you at present. We will review it and merge it if everything looks good.

**Comment by Aleksey28** [comment]
Hello @adityai,

We appreciate you taking the time to improve the examples. Could you please check if it's possible to do this for Chrome? It would be better to enhance the existing example rather than create a new one. For example, Travis's example includes a flow for both browsers.

**Comment by adityai** [comment]
I wanted to simply update the existing chrome version of the bitbucket pipelines example, but I could not get the chrome browser to install on the docker image. But, I was able to install firefox. So, I created a new example with firefox. Please consider adding the firefox example as-is and I will try a different docker image for installing chrome separately. If I can get it working, I will update the chrome example.

**Comment by Bayheck** [comment]
Hello,

I managed to run the example on Chrome and used the following approach in this PR: [https://github.com/DevExpress/testcafe/pull/8346](https://github.com/DevExpress/testcafe/pull/8346)

I will close this PR. Thank you for your contribution.

**Pull request closed without merging**
