### PR TITLE
Update testcafe-hammerhead. Bump version (alpha) (fixes #1442, fixes #1448)

### LINKED ISSUE #1442: Cannot read property 'nextSibling' of undefined
### Are you requesting a feature or reporting a bug?
Reporting a bug

### What is the current behavior?
Always getting the following error

**Errors:**
```
Uncaught Error: Cannot read property 'nextSibling' of undefined
```

### What is the expected behavior?
Test should not fail :)

### How would you reproduce the current behavior (if this is a bug)?
Just run the below code

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://www.zalando.de/nike-sportswear-sneaker-low-metallic-silvervarsity-redblack-ni111s08k-d11.html

Test code

```js
fixture `Example page`
    .page `https://www.zalando.de/nike-sportswear-sneaker-low-metallic-silvervarsity-redblack-ni111s08k-d11.html`;

test('verify redirection', async t => {
    await t
        .debug()
        .click('.z-navicat-header_logoLinkWrapper');

    const location = await t.eval(() => window.location);

    await t.expect(location.pathname).eql('damen-home/');
});
```

### Specify your

* operating system: MacOSX Sierra 10.12.4
* testcafe version: 0.14.0
* node.js version: v7.7.4

### LINKED ISSUE #1448: SyntaxError: "Unexpected token (" while running test
Created from the [disscussion](https://github.com/DevExpress/testcafe/issues/930#issuecomment-297082301)

> @eriklharper commented 5 hours ago • edited
> 
> I'm getting this problem out of the gate on an install with these version params:
> 
> testcafe chrome tests/test1.js
>  Running tests in:
>  - Chrome 57.0.2987 / Mac OS X 10.12.4
> 
>  Getting Started
>  ✖ My first test
> 
>    1) Error on page "https://localhost:8091/login":
> 
>       Uncaught SyntaxError: Unexpected token (
> 
>       Browser: Chrome 57.0.2987 / Mac OS X 10.12.4
> 
> 
> 
>  1/1 failed (7s)
> 
> TestCafe version 0.14.0
> 
> Test Code:
> 
> fixture `Login`
>     .page `http://localhost:8091`;
> 
> test('My first test', async t => {
> });
> 
> With this command:
> 
> testcafe chrome tests/test1.js
> 

> 
>  @georgiy-abbasov commented 5 hours ago
> 
> Hi @eriklharper!
> It's hard to determine the cause of the problem because we don't see your page markup. Could you please provide the page markup, or page url, if it's deployed ?

>  @eriklharper commented an hour ago
> 
> Here's the public URL of the website I'm trying to test: https://staging-edit.meridianapps.com/login

### PR DESCRIPTION
**Pull request by AlexanderMoskovkin**

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
It seems we've broken something: https://travis-ci.org/testcafe-build-bot/testcafe/jobs/228256455#L289
/cc @georgiy-abbasov

**Comment by georgiy-abbasov** [comment]
@AlexanderMoskovkin, it's not relate to PR, Firefox has been updated to version 53 on Sauce Labs side. I'm investigating now

**Comment by AlexanderMoskovkin** [comment]
@georgiy-abbasov [Here](https://travis-ci.org/testcafe-build-bot/testcafe/jobs/228287299#L284) is the same browser (53), but tests are green

**Comment by georgiy-abbasov** [comment]
[Here](https://saucelabs.com/beta/tests/79421b39a67b41aeba6f758df0f662ec) () is green too. It's blinking test

**Comment by AlexanderMoskovkin** [comment]
let's investigate why it's flacky

**Comment by AlexanderMoskovkin** [comment]
There is a [performance issue](https://github.com/DevExpress/testcafe-hammerhead/issues/1111) in `testcafe-hammerhead@10.6.8` so we can't merge it and should wait for the issue resolving

**Pull request closed without merging**
