### PR TITLE
Move report-related errors code to errors/test-run and the runtime errors code to errors/runtime (#347 part 1)

### PR DESCRIPTION
**Pull request by inikulin**
\cc @kirovboris @AlexanderMoskovkin

### CODE REVIEW

**Comment by kirovboris** [comment]
Tests are failed. Please fix it.

**Comment by inikulin** [comment]
@kirovboris More likely we have a problem with saucelabs and travis

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@inikulin FYI: build-bot doesn't restart the tests if they are in progress. I've stopped tests (via travis UI) and restarted them to save our time.

**Comment by inikulin** [comment]
@AlexanderMoskovkin thx

**Comment by kirovboris** [comment]
@inikulin Functional tests is raising the following error:

```AssertionError: object tested must be an array, an object, or a string, but error given```

Is it a tests problem?

**Comment by AlexanderMoskovkin** [comment]
It seems, this is the same problem with functional tests that we saw before (the browser goes to the idle-page from the other browser). We'll research this with @georgiy-abbasov

**Comment by AlexanderMoskovkin** [comment]
> Is it a tests problem?

I'm not sure.I suppose it depends to our `functional-harness` mechanism. The second functional test run is success

**Comment by inikulin** [comment]
@kirovboris 

> Is it a tests problem?

No. Functional tests runs just fine on my side.

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \restart

**Comment by kirovboris** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
