### PR TITLE
Be able to overwrite quarantine threshold via environment variable

### PR DESCRIPTION
**Pull request by link89**
#2329

### CODE REVIEW

**Comment by link89** [comment]
Now we can setting custom quarantine this way.
```bash
QUARANTINE_FAILED_THRESHOLD=10 QUARANTINE_PASSED_THRESHOLD=1 npx testcafe chrome:headless test.js -q

 Running tests in:
 - HeadlessChrome 72.0.3626 / Mac OS X 10.12.6

 test
1
2
3
4
5
6
 ✓ test (unstable)


 1 passed (1s)
```
```javascript
// test.js
import { Selector } from 'testcafe';

let i = 0;

fixture `test`
test('test', async (t) => {
    i++;
    console.log(i);
    await t.expect(i > 5).ok();
})
```

**Comment by link89** [comment]
@AndreyBelym It would be appreciated if you can accept this PR so that we can abort our patch and using official release directly.

**Comment by AndreyBelym** [comment]
Thank you for your contribution, but I've discussed this PR with other team members and we decided that it's better to use already existing configuration mechanisms (CLI flags, runner options, config files) instead of environment variables to implement this feature. Thus we need additional time to discuss implementation details like flag names and so on.

**Comment by link89** [comment]
It is understandable. In my opinion environment variable , which is recommended by https://12factor.net/config , is a handy solution when we don't have resource to do it other way. It is cross platform and in most case won't break compatibility.

**Comment by link89** [comment]
A practical way is to use env vars as "experimental configuration options", which will not guarantee compatibility. And once CLI flags, runner options or config files become available, we can just use env vars as low priority options. @AndreyBelym

**Comment by AlexKamaev** [comment]
@link89 We've discussed this proposal one more time, and decided that at the moment we'll not plan to implement this functionality. We do not want to overload our API until we are sure if the feature is popular. I recommend you create a new feature request using this [form](https://github.com/DevExpress/testcafe/issues/new?template=feature_request.md)
If we see that this proposal is popular, we can reconsider our opinion

**Pull request closed without merging**
