### PR TITLE
[docs] Website: Introduce Blogging Platform

### PR DESCRIPTION
**Pull request by VasilyStrelyaev**
\cc @DevExpress/testcafe-docs 

A part of DevExpress/testcafe-gh-page-assets#19

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
Let's wait till DevExpress/testcafe-gh-page-assets#19 is merged - tests should pass then.

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by VasilyStrelyaev** [comment]
oh, link - not line

**Comment by VasilyStrelyaev** [comment]
The post is a draft BTW - just to make it all build okay.

**Pull request merged**
