### PR TITLE
UseLegacyTestRunError type for legacy API errors and delegate their processing to the legacy code (#374 part2,3)

### PR DESCRIPTION
**Pull request by inikulin**
\cc @kirovboris @AlexanderMoskovkin

### CODE REVIEW

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
FPR

**Comment by kirovboris** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
It seems you have wrong issue link in the title. You are working on #374, not on #372

**Comment by AlexanderMoskovkin** [comment]
lgtm in others

**Comment by inikulin** [comment]
@AlexanderMoskovkin good catch

**Comment by inikulin** [comment]
@AlexanderMoskovkin @kirovboris Can be merged, there were no changes except commit message. Just unstable client test.

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
