### PR TITLE
CLI: Make globally installed testcafe use locally installed version under hood (closes #370)

### LINKED ISSUE #370: CLI: Globally installed testcafe should call locally installed version under hood
This approach is used by mocha, grunt, etc. This way will be able to avoid version conflicts.

### PR DESCRIPTION
**Pull request by inikulin**
\cc @churkin @AndreyBelym

### CODE REVIEW

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
FPR

**Comment by inikulin** [comment]
ping @churkin @AndreyBelym

**Comment by AndreyBelym** [comment]
lgtm

**Comment by churkin** [comment]
lgtm

**Pull request merged**
