### PR TITLE
[docs] Add a post about generating random data

### PR DESCRIPTION
**Pull request by VasilyStrelyaev**

### CODE REVIEW

**Review by andnaz — APPROVED** [review]

**Comment by VasilyStrelyaev** [comment]
@testcafe-build-bot /retest

oh twitter

**Comment by VasilyStrelyaev** [comment]
@testcafe-build-bot \retest

**Comment by VasilyStrelyaev** [comment]
@testcafe-build-bot \retest

**Comment by VasilyStrelyaev** [comment]
what on earth is wrong with Twitter...

**Comment by VasilyStrelyaev** [comment]
I guess we can ignore these errors, they don't make sense, we'll wait and see

**Pull request merged**
