### PR TITLE
Fix incorrect import in embedding utils. Bump version.

### PR DESCRIPTION
**Pull request by inikulin**
\cc @kirovboris @AlexanderMoskovkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by kirovboris** [comment]
Functional tests are failed with assertion error. Is it ok?

**Comment by inikulin** [comment]
@kirovboris Seems like an accidental fail, which is quite uncommon in functional tests. However, it's completely unrelated to PR

**Comment by kirovboris** [comment]
lgtm

**Pull request merged**
