### PR TITLE
Add `selected` attribute to DOM Element snapshot (closes #839)

### LINKED ISSUE #839: Add `selected` attribute to DOM Element snapshot

### PR DESCRIPTION
**Pull request by inikulin**
\cc @AlexanderMoskovkin @AndreyBelym

### CODE REVIEW

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
FYI: I've reproduced this unstable iframe test locally just now and will fix it

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
ping  @AlexanderMoskovkin @AndreyBelym

**Pull request merged**
