### PR TITLE
Added internal method for the getting of the error markup before decorating

### PR DESCRIPTION
**Pull request by kirovboris**
\cc @inikulin @AlexanderMoskovkin

### CODE REVIEW

**Comment by inikulin** [comment]
I guess you need to export `FormattableAdapter` so you will be able to use it externally, like we do for plugin testing utils: https://github.com/kirovboris/testcafe-phoenix/blob/error_formatting/src/index.js#L47 You can export `embeddingUtils`

\r-

**Comment by inikulin** [comment]
Also method is not private, since it will be used externally, so you don't need to add underscore before it's name

**Comment by kirovboris** [comment]
FPR
@VasilyStrelyaev check the strings, please

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by inikulin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
