### PR TITLE
Implemented async-await / promise support for onRequest and onResponse hook methods

### PR DESCRIPTION
**Pull request by miherlosev**

### CODE REVIEW

**Comment by miherlosev** [comment]
FPR

**Comment by AndreyBelym** [comment]
I think we should implement support for async handlers in hammerhead (at least for onRequest - https://github.com/DevExpress/testcafe-hammerhead/blob/b90bb478f63d0df4d133bf8d68d66f023e34ee2a/src/request-pipeline/index.js#L67), and write a test/modify an existing one.

**Comment by kirovboris** [comment]
rebase required

**Comment by miherlosev** [comment]
@kirovboris @AndreyBelym FPR

**Pull request merged**
