### PR TITLE
Fix 'Login via Google' (close #4689)

### LINKED ISSUE #4689: Support cookie sync between multiple opened windows
import { Selector } from 'testcafe';

fixture `Fixture`
    .page('https://google-developers.appspot.com/identity/sign-in/web/demos/signin_contextual_simple?hl=en');

test('test', async t => {
    await t
        .click(Selector('span').withText('Signed in'))
        .typeText(Selector('input[type=email]', '<google-login>'))
        .typeText(Selector('input[type=password]', '<google-password>'))
        .click(Selector('span').withText('Next'));

    const { info } = await t.getBrowserConsoleMessages();

    await t.expect(info[0]).eql('Logged user name');
});

### PR DESCRIPTION
**Pull request by miherlosev**

### CODE REVIEW

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@AndreyBelym FPR

**Pull request merged**
