### PR TITLE
chore: Update minimal required Nodejs version

### PR DESCRIPTION
**Pull request by AlexSkorkin**
## Purpose
Today is the end of life of Nodejs v10.

## Approach
Update minimal required Nodejs version in readme.

## References
[https://github.com/nodejs/Release#release-schedule](https://github.com/nodejs/Release#release-schedule)

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

### CODE REVIEW

**Review by miherlosev — CHANGES_REQUESTED** [review]
Please change version [here](https://github.com/DevExpress/testcafe/blob/master/package.json#L19) too.

**Comment by AlexSkorkin** [comment]
> Please change version [here](https://github.com/DevExpress/testcafe/blob/master/package.json#L19) too.

done

**Review by miherlosev — APPROVED** [review]

**Review by AndreyBelym — APPROVED** [review]

**Comment by miherlosev** [comment]
Rebase please.

**Pull request merged**
