### PR TITLE
Implement 'Compiler options' (close #5519)

### LINKED ISSUE #5519: Support TypeScript 4
### What is your Test Scenario?
We are using TypeScript version 4, which is not compatible with TestCafe's semver of `^3.3`, so code that compiles fine in our repository may not compile when running in TestCafe (die to differences between versions 4 and 3). TestCafe should be able to work with the version of TypeScript in my repository.
 
### What is the Current behavior?
Compilation issues within TestCafe for code that compiles in my repository.
 
### What is the Expected behavior?
Code compiles in TestCafe.
 
### What is your web application and your TestCafe test code?
Normal TestCafe code written in TypeScript, using features supported in TS 4 but not TS 3.

### Steps to Reproduce:
1. Author a TestCafe test in TS using TS 4 compatible features that aren't support in TS 3.
2. Compile files in repository specifying TS 4 dependency - observe no errors.
3. Run TestCafe with file - observe compilation errors.

### PR DESCRIPTION
**Pull request by miherlosev**
Changes:
* fix typo `overriden` -> `overridden`
* allow to specify compiler options (custom compiler options, custom path to TypeScript compiler module, etc.)
* mark 'tsConfigPath` as deprecated option
* display warning message on using deprecated option
* refactor `test/server/helpers/compile.js`, `test/server/helpers/assert-runtime-errors` files

Build for testing
`npm i https://github.com/miherlosev/tmp/files/5382722/testcafe-1.9.4.zip`

### CODE REVIEW

**Comment by miherlosev** [comment]
FPR

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
FPR

**Review by AlexKamaev — APPROVED** [review]

**Review by VasilyStrelyaev — APPROVED** [review]

**Pull request merged**
