### PR TITLE
[docs] Rename index.md to README.md

### PR DESCRIPTION
**Pull request by VasilyStrelyaev**
\cc @DevExpress/testcafe-docs

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
@testcafe-build-bot \retest

**Comment by VasilyStrelyaev** [comment]
Tests will pass after https://github.com/DevExpress/testcafe-gh-page-assets/pull/32 is merged

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by VasilyStrelyaev** [comment]
@testcafe-build-bot \retest

**Pull request merged**
