### PR TITLE
Update saucelabs-connector dependency to version 0.1.3

### PR DESCRIPTION
**Pull request by georgiy-abbasov**

### CODE REVIEW

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
\cc @AlexanderMoskovkin

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
