### PR TITLE
Separate 'saucelabs' and 'phantomjs' providers (part of #705, closes #718)

### LINKED ISSUE #718: renderTemplate recursive replace
`renderTemplate` replaces '{}' in arguments, e.g.
```js
renderTemplate('{1} {2}', ['x {y}' ,'z']) === 'x z {2}'
```

IMHO right behavior is 
```js
renderTemplate('{1} {2}', ['x {y}' ,'z']) === 'x {y} z'
```

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @inikulin @AlexanderMoskovkin 

Also, check the generator for `yeoman`: 
https://github.com/DevExpress/generator-testcafe-browser-provider

And providers based on it:
https://github.com/DevExpress/testcafe-browser-provider-saucelabs
https://github.com/DevExpress/testcafe-browser-provider-phantomjs

### CODE REVIEW

**Comment by AndreyBelym** [comment]
All of packages above are ready for review, except that links are pointing to repositories in my profiles. IMHO we will need to transfer this repos in DevExpress org, but we can do it at any moment later, so criticism is welcome on all except links.

**Comment by AndreyBelym** [comment]
Enabled :anchor:TravisCI  builds for packages.

**Comment by AndreyBelym** [comment]
Repositories moved to DevExpress org, links are fixed, except the one to browser providers docs.

**Comment by inikulin** [comment]
lgtm

**Comment by AndreyBelym** [comment]
What's about packages?

Got an idea for generator package just now: ask the user about if the provider is multi-browser, and alter the usage section of README.md according to their answer. Currently it generates usage docs that is more suitable for simple one-browser provider.

**Comment by inikulin** [comment]
> What's about packages?

Are they ready for review? I don't see notification about PR made to appropriate repos with `\cc`

> Got an idea for generator package just now: ask the user about if the provider is multi-browser, and alter the usage section of README.md according to their answer. Currently it generates usage docs that is more suitable for simple one-browser provider.

:+1:

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
FPR?

**Comment by AndreyBelym** [comment]
I will fix #722 here too.

**Comment by inikulin** [comment]
@AndreyBelym I'd rather go with separate PR. Don't accumulate changes.

**Comment by AndreyBelym** [comment]
FPR then

**Comment by inikulin** [comment]
lgtm

@MargaritaLoseva note that we need to change description for the CLI command

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
