### PR TITLE
t.uploadFile renamed to t.setFilesToUpload including server API (closes #595)

### LINKED ISSUE #595: Rename `t.uploadFile` to `t.setFilesToUpload` (including server API)

### PR DESCRIPTION
**Pull request by georgiy-abbasov**
\cc @AlexanderMoskovkin, @VasilyStrelyaev

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by inikulin** [comment]
Can we postpone merging of this a little bit, pls? I'm about to submit selectors PR and it affects really huge part of current code. It will be a hell for me to rebase on top of all your PRs and it will be easier to apply individual narrowly focused on top of selectors-related changes. Thanks in advance.

**Comment by AlexanderMoskovkin** [comment]
rebase required

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
rebased, please review

**Comment by AlexanderMoskovkin** [comment]
lgtm

/cc @helen-dikareva

**Comment by georgiy-abbasov** [comment]
FPR

**Comment by helen-dikareva** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
