### PR TITLE
feat: added support for JSX in js test files (closes #4817)

### LINKED ISSUE #4817: Cannot resolve `.tsx` files
Support for custom TypeScript compiler options was added in https://github.com/DevExpress/testcafe/pull/3882, but TestCafe seems to restrict TypeScript files to `.ts` only:

https://github.com/DevExpress/testcafe/blob/5b4979d60ced70c54e7e331847c60d90ec8be3cb/src/compiler/test-file/formats/typescript/compiler.ts#L145-L147

This means I cannot write tests to `.tsx` files or import from them, which was one of my main reasons to upvote custom compiler options: https://github.com/DevExpress/testcafe/issues/1845#issuecomment-497704566.

I suppose we could add support for multiple file extensions per compiler and return both `.ts` and `.tsx` from the TypeScript one. I can submit a PR if that's the case.

### PR DESCRIPTION
**Pull request by benmonro**
## Purpose
To allow JSX in Testcafe tests

## Approach
_Describe how your changes address the issue or implement the desired functionality in as much detail as possible._
Was pretty simple, just added the babel-preset-react to the compiler.

## References
_Provide a link to the existing issue(s), if any._
https://github.com/DevExpress/testcafe/issues/5076

## Pre-Merge TODO
- [x] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

### CODE REVIEW

**Comment by benmonro** [comment]
@AlexKamaev all but one test is failing, when I run the tests locally it takes a VERY long time to run so I had to cancel it. not sure why that test is even failing, it seems to be unrelated.  can you retrigger the build?

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by SimonKlausLudwig** [comment]
any update on this feature ?

**Comment by wentwrong** [comment]
Hi @SimonKlausLudwig,

There are no updates because this feature (support of test files in jsx/tsx format) is already implemented in TestCafe in `v1.8.6` and later versions.

**Pull request merged**
