### PR TITLE
Remove collaborators list, because we have org team now.

### PR DESCRIPTION
**Pull request by inikulin**
\cc @VasilyStrelyaev

### CODE REVIEW

**Comment by inikulin** [comment]
ping @VasilyStrelyaev

**Comment by VasilyStrelyaev** [comment]
mmm... what does this have to do with me?

**Comment by VasilyStrelyaev** [comment]
(I must be missing something)

**Comment by inikulin** [comment]
Somehow you are our chief tech writer and somehow this is docs. So, it's just one of those moments then we enjoy bureaucracy in it's best :sunglasses:

**Comment by VasilyStrelyaev** [comment]
Oh, yeah, I know this tech writer stuff.
It just seems I don't understand what you are doing here.
I guess you remove everyone from collaborators since all the necessary rights are provided via our DevExpress account.
And you say this is **docs**... Please explain.

**Comment by inikulin** [comment]
You such a party breaker! :weary: Collaborators were **documented** in this so we'll be able to add them to the new projects and it was a general place to store GH nicknames of the team members. Since now we've moved to the org account we don't need it anymore. ~~Just merge it already~~

**Comment by VasilyStrelyaev** [comment]
Meh!

**Comment by inikulin** [comment]
THANK YOU! :trophy:

**Pull request merged**
