### PR TITLE
Implement `Selector` (part7, closes #574)

### LINKED ISSUE #574: APIv2: implement `Selector` hybrids
Unlike hybrids `Selector` returns element descriptor object. Selectors and their results can be used as action selectors. By default it will use our waiting heuristics for element to appear in the DOM. Selectors can return DOM node or `null`. If you want immediate value, you can use `.now` postfix of selector:
```js
const getElement = Selector(id => document.getElementById(id));
const elementNow = await getElement('yo').now;
```

- [x] Throw if hybrid returns DOM node
- [x] `Client code` -> `Hybrid function code`
- [x] Implement  basic `Selector` API
- [x] Node snapshots
  - [x] Element
       -  [x] `nodeType`
       -  [x] `id`
       -  [x] `tagName`
       -  [x] `attributes`
       -  [x] `namespaceURI`
       -  [x] `hasChildNodes`
       -  [x] `childNodeCount`
       -  [x] `hasChildElements`
       -  [x] `childElementCount`
       -  [x] `visible`
       -  [x] `scrollWidth`
       -  [x] `scrollHeight`
       -  [x] `scrollLeft`
       -  [x] `scrollTop`
       -  [x] `offsetWidth`
       -  [x] `offsetHeight`
       -  [x] `offsetLeft`
       -  [x] `offsetTop`
       -  [x] `clientWidth`
       -  [x] `clientHeight`
       -  [x] `clientLeft`
       -  [x] `clientTop`
       -  [x] `focused`
       -  [x] `value`
       -  [x] `checked`  
       -  [x] `boundingClientRect`
       -  [x] `textContent`
       - [x] `classNames`
       - [x] `innerText`
       - [x] `style`
  - [x] Comment
  - [x] Text
  - [x] DocumentFragment
  - [x] Document
  - [x] Methods: `getParentNode`, `getChildNode(i)`, `getChildElement(i)`, `hasClass` 
- [x] Rename `Hybrid` to `ClientFunction`
- [x] Forbid `function` return value for Hybrids: we can't determine kind of hybrid ahead of time

- [x] Cross-browser `innerText`
- [x] Get rid of `Hybrid` term. Introduce `ClientFunctionFactory`s
- [x] Error text adjustment for `Hybrids` and `Selector`
- [x] Selector from string

- [x] Node existence awaiting
- [x] `clientFunction.with()`
- [x] `selector.with({ visibilityCheck: Boolean})` and remove  `t.waitForElement`
- [x] `selector.with({timeout: 0})`
- [x] Use selectors machinery for action selectors
- [x] Auto-conversion in actions: function to selector if passed as parameter.

- [x] Throw if returns anything except `null`, `undefined` or DOM node
- [x] Function `scopeVars`
- [x] Selector result as action parameter
- [x] `t.select`

- [x] Figure out behavior then page load occurs during selector execution

- Select by text command and  `t.selectByText`  (moved to #615)

### PR DESCRIPTION
**Pull request by inikulin**
In this final part:
- Cross-page behavior
- `t.select`

\cc @helen-dikareva @AlexanderMoskovkin @VasilyStrelyaev

### CODE REVIEW

**Comment by inikulin** [comment]
ping @helen-dikareva @AlexanderMoskovkin @VasilyStrelyaev

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by helen-dikareva** [comment]
I think we need to add test with expired of global timeout waiting for element

**Comment by helen-dikareva** [comment]
other lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
