### PR TITLE
feat: added docs for @testing-library/testcafe

### PR DESCRIPTION
**Pull request by benmonro**
## Purpose
_Describe the problem you want to address or the feature you want to implement._
To add docs in the integrations section for testcafe testing library.

## Approach
_Describe how your changes address the issue or implement the desired functionality in as much detail as possible._
Added the docs to the readme and the integrations folder.  I attempted to test the docs site myself but i kept getting an error from jekyll: 

```
Traceback (most recent call last):
        23: from /usr/local/bin/jekyll:23:in `<main>'
        22: from /usr/local/bin/jekyll:23:in `load'
        21: from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.0.1/exe/jekyll:11:in `<top (required)>'
        20: from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.0.1/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
        19: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler.rb:107:in `setup'
        18: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/runtime.rb:20:in `setup'
        17: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/runtime.rb:108:in `block in definition_method'
        16: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/definition.rb:226:in `requested_specs'
        15: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/definition.rb:237:in `specs_for'
        14: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/definition.rb:170:in `specs'
        13: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/definition.rb:247:in `resolve'
        12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/definition.rb:744:in `converge_locked_specs'
        11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/definition.rb:744:in `each'
        10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/definition.rb:758:in `block in converge_locked_specs'
         9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/source/git.rb:167:in `specs'
         8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/source/path.rb:100:in `local_specs'
         7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/source/git.rb:200:in `load_spec_files'
         6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/source/path.rb:163:in `load_spec_files'
         5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/source/path.rb:126:in `expanded_path'
         4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/source/git.rb:93:in `install_path'
         3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/source/git.rb:225:in `revision'
         2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/source/git/git_proxy.rb:64:in `revision'
         1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/source/git/git_proxy.rb:192:in `find_local_revision'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/source/git/git_proxy.rb:235:in `allowed_in_path': The git source https://github.com/VasilyStrelyaev/jekyll-redirect-from is not yet checked out. Please run `bundle install` before trying to start your application (Bundler::GitError)
```
## References
_Provide a link to the existing issue(s), if any._

## Pre-Merge TODO
- [ x] Write tests for your proposed changes
- [ x] Make sure that existing tests do not fail

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
Thank you for your contribution, @benmonro!
I made some edits, please see if they are okay.

**Comment by benmonro** [comment]
@VasilyStrelyaev yep looks good to me, made one little tweak to add 'drives tests from the user's perspective' 

Thanks!

**Comment by VasilyStrelyaev** [comment]
Thank you!

**Comment by benmonro** [comment]
@VasilyStrelyaev I'm not seeing the testcafe stuff on this page: https://devexpress.github.io/testcafe/documentation/recipes/

is there another place where we need to add the link for testcafe testing library?

**Comment by VasilyStrelyaev** [comment]
No, we just need to update the website. We usually do this every other week.

**Pull request merged**
