### PR TITLE
[docs] CLI - example for T and F options updated

### PR DESCRIPTION
**Pull request by MargaritaLoseva**
/cc @DevExpress/testcafe-docs

### CODE REVIEW

**Comment by inikulin** [comment]
Tests fail, more likely rebasing on top of https://github.com/DevExpress/testcafe/pull/606 will fix it

**Comment by inikulin** [comment]
Everything else - lgtm

**Comment by kirovboris** [comment]
lgtm

**Comment by MargaritaLoseva** [comment]
Tests fail because we have broken links in GS that is already merged.

**Comment by inikulin** [comment]
Odd, can you fix them in context of this PR, please?

**Comment by MargaritaLoseva** [comment]
@testcafe-build-bot /retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by VasilyStrelyaev** [comment]
lgtm

**Pull request merged**
