### PR TITLE
Get rid of last legacy dependencies in the client code (closes #673)

### LINKED ISSUE #673: We need to completely separate client legacy code from the new one and move all legacy code to separate package

### PR DESCRIPTION
**Pull request by AlexanderMoskovkin**

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
FPR

**Comment by inikulin** [comment]
lgtm 

@AlexanderMoskovkin Should someone else take a look?

**Comment by inikulin** [comment]
\cc @helen-dikareva @georgiy-abbasov

**Comment by helen-dikareva** [comment]
lgtm

**Comment by georgiy-abbasov** [comment]
I think, [this](https://github.com/AlexanderMoskovkin/testcafe-phoenix/blob/gh-673/src/test-run/index.js#L65) line is redundant. I'm checking without this, if it will be ok, we should get rid of this line in next another PR

**Comment by inikulin** [comment]
> I think, this line is redundant.

Correct. We can wait till @AlexanderMoskovkin will be back from vacation and then merge it

**Comment by georgiy-abbasov** [comment]
> I think, this line is redundant. I'm checking without this

Tests are ok, overall.
@inikulin, you know better, what we should do.

**Comment by inikulin** [comment]
> @inikulin, you know better, what we should do.

wrong

**Comment by AlexanderMoskovkin** [comment]
> I think, this line is redundant

Yes, you are right. I'll remove this line a little later

**Comment by georgiy-abbasov** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Pull request merged**
