### PR TITLE
-v option added

### LINKED ISSUE #369: CLI docs missing `-v, --version` option description

### PR DESCRIPTION
**Pull request by MargaritaLoseva**
Closes #369

### CODE REVIEW

**Comment by MargaritaLoseva** [comment]
//cc @inikulin @VasilyStrelyaev

**Comment by MargaritaLoseva** [comment]
@testcafe-build-bot \ retest

**Comment by inikulin** [comment]
lgtm

**Comment by VasilyStrelyaev** [comment]
lgtm

**Pull request merged**
