### PR TITLE
Update hammerhead (v14.10.1)

### PR DESCRIPTION
**Pull request by miherlosev**
Update is necessary to apply changes related to the 'multi-browser-feature' feature.

### CODE REVIEW

**Comment by AlexKamaev** [comment]
Could we please wait for https://github.com/DevExpress/testcafe-hammerhead/pull/2160 ?

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
Waiting for https://github.com/DevExpress/testcafe/pull/4420

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Pull request merged**
