### PR TITLE
0.19.1-dev20180305

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

**Comment by AndreyBelym** [comment]
Tests failed because of changes in script processor. See the test data https://github.com/DevExpress/testcafe/blob/master/test/server/data/client-fn-compilation/basic/expected.js https://github.com/DevExpress/testcafe/blob/master/test/server/data/client-fn-compilation/basic/expected.js

**Comment by miherlosev** [comment]
@LavrovArtem need to change code in provided links

**Comment by miherlosev** [comment]
@AndreyBelym 
As I understand the https://github.com/DevExpress/testcafe/blob/master/test/server/data/client-fn-compilation/basic/expected-node10.js related to node 0.10.0 version.
At present, we don't support this version. Can we remove this file?

**Comment by AndreyBelym** [comment]
Yes, we can safely remove it.

**Pull request merged**
