### PR TITLE
Fix some unstable qunit tests

### PR DESCRIPTION
**Pull request by AlexanderMoskovkin**

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
It were seven successful client tests runs in a raw. Let's review this amazing public fix :-)
/cc @helen-dikareva @georgiy-abbasov

**Comment by AlexanderMoskovkin** [comment]
ping @helen-dikareva @georgiy-abbasov

**Comment by georgiy-abbasov** [comment]
lgtm

**Comment by helen-dikareva** [comment]
it's really genius)

**Pull request merged**
