### PR TITLE
[docs] Added new cloud browser plugin LambdaTest

### PR DESCRIPTION
**Pull request by kanhaiya15**
### Description
Updated docs for cloud browser plugin support LambdaTest
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:
- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
Here already opened an issue at TestCafe #3896

### CODE REVIEW

**Comment by AndreyBelym** [comment]
Thank you for your contribution. I see that LambdaTest provides a free plan, so I want to test your plugin before including it to our list.

**Comment by kanhaiya15** [comment]
Hi @AndreyBelym , Thanks for reviewing the PR!. Can you please sign up on our platform? and let me know, We will process your open source account in no time. [Sign up here](https://accounts.lambdatest.com/register) :point_left: . I appreciate your help, TIA.

**Comment by kanhaiya15** [comment]
Hi @AndreyBelym, I see that you have registered on our platform. We have granted access to your user account. Looking forward to taking this further.

**Comment by kanhaiya15** [comment]
Thanks a ton. For looking into so fast. I appreciate your support.

**Pull request merged**
