### PR TITLE
[docs] Add my TestCafe Cucumber steps plugin

### PR DESCRIPTION
**Pull request by Marketionist**
**This pull request adds my TestCafe Cucumber steps plugin to the community plugins list**

Associated issue: https://github.com/DevExpress/testcafe/issues/4674

### CODE REVIEW

**Comment by Marketionist** [comment]
@AlexSkorkin @AndreyBelym please review

**Comment by Marketionist** [comment]
@VasilyStrelyaev please take a look - I'd be happy to merge if it's ok

**Comment by VasilyStrelyaev** [comment]
Thank you for your contribution.
I have also added a link to [gherkin-testcafe](https://github.com/kiwigrid/gherkin-testcafe).

**Comment by VasilyStrelyaev** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
Thank you for your contribution. Tests are broken due to a third-party module update. We will fix it and merge the PR.

**Comment by Marketionist** [comment]
@AlexSkorkin @VasilyStrelyaev @AndreyBelym @kirovboris thank you a lot for taking a look at this PR!

**Pull request merged**
