### PR TITLE
mousemove event sent to wrong element during dragging (close #372)

### LINKED ISSUE #372: 'mousemove' event sent to wrong element during dragging
`act.drag(element1, element2)` always sends `mousemove` events to `element1`, even if `element1` is n't actually dragging. This behavior appeared after refactoring, and it breaks ASP test on [Calendar demo](https://demos.devexpress.com/ASPxEditorsDemos/ASPxCalendar/Features.aspx).

Test uses following code to select days cells from 1 to 15:
```js
act.drag(getCalendar().getNumberCell(1), getCalendar().getNumberCell(15))
```
Client code is listening to `mousemove` events on different cells to update selection, so because we are sending `mousemove` only to start element, selection always contains only day 1.

### PR DESCRIPTION
**Pull request by helen-dikareva**
\cc @AlexanderMoskovkin @AndreyBelym

### CODE REVIEW

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by AndreyBelym** [comment]
lgtm. Fixes ASP test.

**Pull request merged**
