### PR TITLE
Redesign legacy errors (closes #685)

### LINKED ISSUE #685: Redesign error messages
New look:

- [x] New API errors
- [ ] Legacy API errors

### PR DESCRIPTION
**Pull request by inikulin**
\cc @kirovboris @AlexanderMoskovkin

### CODE REVIEW

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by kirovboris** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
It's an unstable qunit test, so we can rebase. I've added a timeout for qunit tests recently, so it seems there are some problems with this on slow machines, I'll investigate this

**Comment by inikulin** [comment]
@AlexanderMoskovkin do you mind to review? =)

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
