### PR TITLE
0.20.4

### PR DESCRIPTION
**Pull request by miherlosev**
@AndreyBelym @VasilyStrelyaev

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
We have to wait until https://github.com/DevExpress/testcafe/issues/2216 is documented, don't we?

**Comment by AndreyBelym** [comment]
AFAIR we've already discussed it with @kirovboris, and decided to release without docs for #2216.

**Comment by miherlosev** [comment]
Ok, then I will remove from changelog an information about #2216

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by AndreyBelym** [comment]
Tests in PR are fine, let's merge it and wait for `master` badges to update:
<a href="https://ci.appveyor.com/project/DevExpress/testcafe">Functional Windows desktop</a>
<a href="https://travis-ci.org/DevExpress/testcafe">All Travis tasks (server, client, functional: mobile, macOS, Edge)</a>

**Pull request merged**
