### PR TITLE
Right click command (#441)

### PR DESCRIPTION
**Pull request by helen-dikareva**
\cc @AlexanderMoskovkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
lgtm

/cc @AndreyBelym @VasilyStrelyaev

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
lgtm

**Pull request merged**
