### PR TITLE
[docs] Update the website 3/20/2020

### PR DESCRIPTION
**Pull request by VasilyStrelyaev**
Merge to update the website (but first check carefully).

Preview at: https://vasilystrelyaev.github.io/testcafe/

* Redesigned the header, footer, and both mobile menus
* New Media section with [Community Blogs](https://vasilystrelyaev.github.io/testcafe/media/community/) and [Courses](https://vasilystrelyaev.github.io/testcafe/media/courses/)
* Changed how the TOC tree is generated in the docs

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
Please double-check that the existing pages are not broken

**Comment by andnaz** [comment]
@VasilyStrelyaev 
**Link - Blog post** should lead to a blog post
**Link - Published on** should lead to the main page of a website

Sorry if it wasn't clear

image

**Comment by andnaz** [comment]
@helen-dikareva We were going to add the Blog page and make links to user content available from this page. But at the moment we don't have any blog posts so we decided to add Media firstly.

We didn't plan to have Media in the header, but it also works fine for me. 

@kirovboris @alexphilin Are you ok with having these buttons in the header? Blog, Media, Docs, FAQ, Support, TestCafe Studio

**Comment by kirovboris** [comment]
No problem with that.

**Pull request merged**
