### PR TITLE
Fix a conflict with Jest type definitions (closes #4405)

### LINKED ISSUE #4405: Typescript error when using testcafe version 1.6.0
### What is the Current behavior?

 * I am currently using create react app  plus `"typescript": "3.6.0"`. When I upgraded from `version 1.5.0` to `v1.6.0` and I ran my tests I get this error:
```
 Property 'page' does not exist on type 'It'.
Property 'page' does not exist on type 'It'.
Property 'page' does not exist on type 'It'.
```
 Looks like this is similar to or maybe the same as the [declare var test on global scope issue](https://github.com/DevExpress/testcafe/issues/1537)

### What is the Expected behavior?

I would expect to run the tests.

### Your Environment details:
 
* testcafe version:                  `testcafe -v1.6.0` 
* typescript: `3.6.0`
* node.js version:                     `node -v10.15.3`
* browser name and version:  I run it headless
* platform and version:          macOS Mojava 10.14.6
* other:

### PR DESCRIPTION
**Pull request by AndreyBelym**
Closes #4405.

### CODE REVIEW

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Comment by vire** [comment]
I've tried manually edit the `node_modules/testcafe/ts-defs/index.d.ts` chaning `export` to `declare` but problem is still present

node_modules/testcafe/ts-defs/index.d.ts 


image

**Comment by AndreyBelym** [comment]
@vire, this change can fix only starting TypeScript tests with TestCafe. Code completion never worked smoothly with Jest, since its type definitions from `@types/jest` are loaded automatically unlike our definitions which built into the `testcafe` package. You can try to add `import { Selector } from 'testcafe'` to load TestCafe's type definitions.

**Comment by vire** [comment]
@AndreyBelym 

Actually code-completion would be the less severe problem - but with `compiler` complaining about not recognizing `test` as `testcafe` typed fn

image

**Comment by vire** [comment]
Maybe worth to consider would be - bail on `global` and use

`import {Selector, test, fixture} from ' testcafe'` which would solve the types problem once for all, but I know most programmers could have a very long debate on this :/

**Pull request merged**
