### PR TITLE
label with attribute tabIndex should be focused (closes #3501)

### LINKED ISSUE #3501: It's not possible to focus on label with tabIndex=0 and "for" attribute
### What is your Test Scenario?
I have a radio button associated with label using "for" attribute. Label also has "tabIndex" attribute to be focused. When i click on this label using testcafe, it not became focused. But in real situation it is.
 
### What is the Current behavior?
Currently this test always fails.
 
### What is the Expected behavior?
When i'm clicking on this label by mouse, label became focused.
 
### What is your web application and your TestCafe test code?

My component looks like this one

```html
<div>
 <label for="radio" tabIndex="0">...</label>
 <input type=radio id=radio>
</div>
```

```scss
label {
  background: red;
  &:focus {
    outline: 0;
    background: green;  // just to check whether this component is focused
  }
}
```

And test case is:

```js
const label = Selector('label');
test('...', async t => {
  await t
     .click(label)
     .expect(label.focused)
     .ok();
});
```

### Steps to Reproduce:
1. Run test

### Workaround

When i replacing label with span, it works (but i need to check radio button by myself because "for" attribute does not work for spans).

### Your Environment details:
 
* testcafe version:                   0.22
* node.js version:                    10.13.0
* browser name and version: chrome 72
* platform and version:         macOS 10.13.6

### PR DESCRIPTION
**Pull request by AlexKamaev**
then please review this one https://github.com/DevExpress/testcafe-hammerhead/pull/2054

### CODE REVIEW

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Comment by AlexKamaev** [comment]
You can review this PR, the Travis tests passed, I don't know why they are displayed as failed.

**Comment by AndreyBelym** [comment]
\cc @miherlosev

**Pull request merged**
