### PR TITLE
ResizeWindow, ResizeWindowToFitDevice and TakeScreenshot commands improvements (close #584, close #585)

### LINKED ISSUE #584: `resizeWindowToFitDevice` should have options object as second argument
Instead of:
```js
await t.resizeWindowToFitDevice('iPhone', true);
```

it should be

```js
await t.resizeWindowToFitDevice('iPhone', { portraitOrientation: true });
```

It should be Options object with property validation mechanism. We've already discussed it in https://github.com/DevExpress/testcafe/pull/543#discussion_r65533925

### LINKED ISSUE #585: We don't have functional tests for `takeScreenshot` and `resizeWindow` agument errors

### PR DESCRIPTION
**Pull request by helen-dikareva**
/cc @inikulin @AlexanderMoskovkin @VasilyStrelyaev

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
FPR

**Comment by helen-dikareva** [comment]
ping @inikulin

**Comment by inikulin** [comment]
lgtm

**Pull request merged**
