### PR TITLE
[docs] Add new contributors to README.md

### PR DESCRIPTION
**Pull request by Marketionist**
**This pull request adds new contributors to README.md**

### CODE REVIEW

**Comment by Marketionist** [comment]
Tests fail because of a broken link (that is not related to this PR).
```
[23:12:05] URL: http://localhost:8080/testcafe/blog/testcafe-v1-1-0-released.html
[23:12:05] Broken links:
[23:12:05] https://github.com/vitalics
[23:12:05] undefined
```
To stay on a safe side I checked the link `https://github.com/vitalics` - it is valid and works ok. @VasilyStrelyaev please review and merge if ok.

**Comment by VasilyStrelyaev** [comment]
@testcafe-build-bot \retest

**Comment by Marketionist** [comment]
Fixed, @AlexSkorkin please review again

**Comment by VasilyStrelyaev** [comment]
Thanks for the update!

**Pull request merged**
