### PR TITLE
Add type definitions for RequestOptions and ResponseMock (closes #5108)

### LINKED ISSUE #5108: Add type definitions for RequestMock respond/onRequestTo/RequestOptions
This is more a refactor than a bug, but it felt more like a bug than a feature :P Hope that's ok.

### What is your Test Scenario?
Trying to get autocompletion/type-safety for the `.respond((req, res) => {})` and `.onRequestTo((req) => boolean)` methods of `RequestMock`.
 
### What is the Current behavior?
Currently these function's arguments have types `any`:
https://github.com/DevExpress/testcafe/blob/e5d2081bd7f40ca99769402271fc65293260ea12/ts-defs-src/test-api/request-hook.d.ts#L149-L162
 
### What is the Expected behavior?
They should have types `RequestOptions`, as defined here: https://devexpress.github.io/testcafe/documentation/reference/test-api/requestmock/respond.html#requestoptions , and some other type for `Response`.
 
### What is your web application and your TestCafe test code?
Not really applicable, but https://github.com/internetarchive/bookreader
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

https://github.com/internetarchive/bookreader/pull/314/files#diff-53a5fe68f6659bdf074d53e1ac18547b

Here's a minimal snippet:

```js
import { RequestMock } from 'testcafe';

RequestMock()
.onRequestTo(req => req.url) // No autocomplete after `req.`
.response((req, res) => res.setBody('foo')); // No autocomplete for `res.`
```

</details>

<details>
<summary>Your complete configuration file (if any):</summary>

NA

</details>

<details>
<summary>Your complete test report:</summary>

NA

</details>

<details>
<summary>Screenshots:</summary>

NA

</details>

### Steps to Reproduce:

1. Paste the minimal code snippet in vscode
2. Try to get autocomplete
 
### Your Environment details:
 
* testcafe version:                   1.8.1
* node.js version:                    12.4.0
* command-line arguments:  NA
* browser name and version: NA
* platform and version:          Win10
* other:                                   None

### PR DESCRIPTION
**Pull request by cdrini**
## Purpose
Add type definitions for `RequestOptions` and `ResponseMock`, and update type definitions for `RequestMock.onRequestTo` and `RequestMock.respond` accordingly.

## Approach
- Copied text/types from https://devexpress.github.io/testcafe/documentation/reference/test-api/requestmock/respond.html#requestoptions
- Also took a look at the src:
   - RequestOptions: https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/request-pipeline/request-options.ts
   - ResponseMock: https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/request-pipeline/request-hooks/response-mock.ts
- Not entirely sure how to test these in any feasible way. I confirmed they worked by modifying the .d.ts in node_modules of an existing project with the above changes, and confirming that auto-completion works, but not sure if the existing tests will catch anything odd here.
- I use the type definitions for autocompletion in a non-typescript project, so not sure if there's something here that might cause problems for actual typescript users.

## References
Closes #5108

## Pre-Merge TODO
- [x] Write tests for your proposed changes
    - There were some existing tests here; not sure what tests to add for type checking except just normal tests?
- [x] Make sure that existing tests do not fail

### CODE REVIEW

**Comment by cdrini** [comment]
@testcafe-build-bot retest

**Comment by cdrini** [comment]
@testcafe-build-bot retest

**Comment by cdrini** [comment]
Testing seems to be stuck?

**Comment by AlexKamaev** [comment]
@cdrini I restarted the stuck tests. It seems that only Travis' [server tests](https://travis-ci.org/github/testcafe-build-bot/testcafe/jobs/690932724) fail now

**Comment by cdrini** [comment]
Thanks @AlexKamaev ! I think this is ready for review now :+1:

(The typings actually caught a bug! \o/)

**Comment by ruimarques** [comment]
@cdrini I wonder if you somehow missed adding `isAjax` to `RequestOptions` type?
The following used to compile but now I get typescript error `Property 'isAjax' does not exist on type 'RequestOptions'.`

```
RequestMock()
      .onRequestTo(req => {
        if (req.isAjax) {
         // do something
        }

      })
```

According to documentation isAjax should exist:

https://devexpress.github.io/testcafe/documentation/reference/test-api/requestmock/onrequestto.html

**Comment by cdrini** [comment]
I based this off https://devexpress.github.io/testcafe/documentation/reference/test-api/requestmock/respond.html#requestoptions ; it looks like it's missing from those docs as well. It is in the src code: https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/request-pipeline/request-options.ts#L19

**Comment by miherlosev** [comment]
You're right, the description of the `isAjax` property is missing in the documentation. I created a separate [issue](https://github.com/DevExpress/testcafe/issues/5562)) for this.

**Pull request merged**
