### PR TITLE
Introduce TestRunErrorFormattableAdapter (#374 part4)

### PR DESCRIPTION
**Pull request by inikulin**
\cc @kirovboris @AlexanderMoskovkin

### CODE REVIEW

**Comment by kirovboris** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by kirovboris** [comment]
lgtm

**Pull request merged**
