### PR TITLE
Move to testcafe-hammerhead v.3.x.x (close #209)

### LINKED ISSUE #209: Move to testcafe-hammerhead v.3.x.x
https://github.com/DevExpress/testcafe-hammerhead/pull/310

### PR DESCRIPTION
**Pull request by helen-dikareva**
/cc @AlexanderMoskovkin  @inikulin

### CODE REVIEW

**Comment by inikulin** [comment]
@helen-dikareva Shouldn't we change anything in code because of BC in hammerhead?

**Comment by helen-dikareva** [comment]
changes are in recorder only

**Comment by inikulin** [comment]
lgtm then

**Comment by AlexanderMoskovkin** [comment]
waiting for the tests result

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
