### PR TITLE
[docs] Refactor CI topics

### PR DESCRIPTION
**Pull request by VasilyStrelyaev**
\cc @DevExpress/testcafe-docs 

http://strelyaev-w8:8080/testcafe/documentation/continuous-integration/

### CODE REVIEW

**Comment by helen-dikareva** [comment]
Maybe [this recipe](https://devexpress.github.io/testcafe/documentation/recipes/running-tests-using-travis-ci-and-sauce-labs.html) should be in CI section too?

**Comment by kirovboris** [comment]
@VasilyStrelyaev Let's not to mix pull requests, because  regrouping other recipes is out-of-scope for this pr.

**Comment by VasilyStrelyaev** [comment]
@testcafe-build-bot \retest

**Comment by AlexSkorkin** [comment]
Go ahead and merge it!

**Pull request merged**
