### PR TITLE
ability to log stdout and stderr of tested-app (closes #5423)

### LINKED ISSUE #5423: Ability to log stdout and stderr of tested-app (appCommand child process)
The ability to view the stdout and stderr of the test-app (appCommand child process) would provide value for debugging the application under test, especially in the case where the appCommand exits due to failure.  At the moment, the implementation rejects with the error at exit and effectively swallows the logs.  The output leading up to the appCommand failure would provide value in debugging.

### What is your Test Scenario?
The test-app (appCommand) fails on start-up or during execution.

### What are you suggesting?
Introducing configuration to allow for the ability to log the stdout and/or stderr of the test-app (appCommand child process).  The configuration would be used as flags for logging the stdout and stderr on the callback (3rd parameter) of the exec invocation for producing/running the appCommand.

The following code in particular:
https://github.com/DevExpress/testcafe/blob/master/src/runner/tested-app.ts#L49-L55

I can work to contribute this if there is appetite for it.

### What alternatives have you considered?
Adjusting the application code to write to disk or running the application under test outside of testcafe.  However, these solutions seem like unfavorable workarounds.

### PR DESCRIPTION
**Pull request by kubejm**
## Purpose
The ability to view the stdout and stderr of the tested-app (appCommand child process) would provide value for debugging the application under test, especially in the case where the appCommand exits due to failure. At the moment, the implementation rejects with the error at exit and effectively swallows the logs. The output leading up to the appCommand failure would provide value in debugging.

## Approach
Utilize the `debug` package (e.g. `debugLogger`) to log the stdout and stderr of the tested-app via the exec callback, which will allow users of testcafe to toggle the logging of this information via the `DEBUG` environment variable. 

## References
Addresses: https://github.com/DevExpress/testcafe/issues/5423

### CODE REVIEW

**Comment by kubejm** [comment]
Hi @AndreyBelym,

Thanks for taking a look and working through this!  Let me know if I can do anything to assist you further.

**Review by AndreyBelym — APPROVED** [review]

**Comment by AndreyBelym** [comment]
Thank you for your contribution 👍

**Comment by joeosburn** [comment]
@AndreyBelym Thanks for your work on this. Would you be able to provide an example of how someone would utilize your work here?

I'm using testcafe with a runner script, with the `startApp` function being called like this:
```
.startApp('npm run dev')
```
I'm trying to figure out how I can see the stdout/stderr output from `npm run dev`

Thanks!

**Comment by AndreyBelym** [comment]
@joeosburn You can set the `DEBUG` environment variable to `"testcafe:tested-app:*"` to output both stderr and stdout, or output only stderr/stdout by setting it to `"testcafe:tested-app:stderr"`/`"testcafe:tested-app:stdout"`

**Comment by joeosburn** [comment]
Thanks @AndreyBelym. Just what I needed.

**Comment by TiraO** [comment]
@AlexKamaev is there currently any way to configure this logging in the testcaferc file?

**Comment by miherlosev** [comment]
Hi @TiraO,

Logging is enabled by the [debug](https://www.npmjs.com/package/debug) module. The only way to configure it is to set the environment variable to `DEBUG`. Check the following comment to see how to output the debug information on running a test application: [https://github.com/DevExpress/testcafe/pull/5431#issuecomment-1034610852](https://github.com/DevExpress/testcafe/pull/5431#issuecomment-1034610852).

**Pull request merged**
