### PR TITLE
Fixed client tests settings for Sauce Labs (closes #502)

### LINKED ISSUE #502: Repare saucelabs browser-matrix for client tests
now it shows the result for desktop browsers or mobile browsers only but should show for both

(i've broken it in #478)

### PR DESCRIPTION
**Pull request by georgiy-abbasov**

### CODE REVIEW

**Comment by georgiy-abbasov** [comment]
Now client tests status badge should look like:
 [Sauce Test Status](https://saucelabs.com/u/testcafe-pr)

**Comment by georgiy-abbasov** [comment]
\cc @inikulin, @AlexanderMoskovkin

**Comment by AlexanderMoskovkin** [comment]
> Now client tests status badge should look like:

You image in the comment shows a badge for tests from an other PR (for the current running tests) and it doesn't contain results from mobile browsers at the moment.
But I've checked this will be ok after we merge this PR.

**Comment by AlexanderMoskovkin** [comment]
lgtm

@helen-dikareva please, review this

**Comment by georgiy-abbasov** [comment]
@AlexanderMoskovkin, yes, at current moment this badge displays latest statistics on `testcafe-pr` (all browsers were on badge, when i posted).

**Comment by helen-dikareva** [comment]
lgtm

**Pull request merged**
