### PR TITLE
[docs] Website - Introduce build modes

### PR DESCRIPTION
**Pull request by VasilyStrelyaev**
\cc @DevExpress/testcafe-docs 

Please **double-check** this.

I've introduced three build modes: 

* `testing` - when the website is built for testing
* `development` - when the website is built for local deployment
* `production` - when the website is built for publishing

Use cases:

* blog comments - won't be added in `testing` mode; in `development` mode, comments from a 'staging' thread are displayed; in `production` mode, public comment threads are displayed.
* Google Analytics is added only in `production` mode.
* ...

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
Did I get it right that tests fail because I can't use `spawn(..., { env : { ... } }` in Travis - I can only assign environment variables in `.travis.yml`?

**Comment by VasilyStrelyaev** [comment]
okay, trying it with `.travis.yml`

**Comment by inikulin** [comment]
lgtm

**Comment by VasilyStrelyaev** [comment]
WIP!

**Comment by VasilyStrelyaev** [comment]
have to make sure the spawned process inherits environment variables and it's actually built in `testing` mode.

**Comment by VasilyStrelyaev** [comment]
yep, it does

**Comment by VasilyStrelyaev** [comment]
FPR

**Comment by inikulin** [comment]
lgtm, but can you add comment to gulp file about possible build configurations and how they affect site functionality, please?

**Comment by VasilyStrelyaev** [comment]
Meh, I surely can but, most probably, noone will update this comment ever.
The way build configurations affect site functionality is implemented in a different place - in website assets.
Who will remember to update a comment in `Gulpfile.js` when changing website assets?

**Comment by inikulin** [comment]
@VasilyStrelyaev we've just talked to move website assets to this repo, so it makes sense IMO

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
lgtm

**Pull request merged**
