### PR TITLE
Update hammerhead. Bump alpha version

### PR DESCRIPTION
**Pull request by AlexanderMoskovkin**

### CODE REVIEW

**Comment by inikulin** [comment]
@AlexanderMoskovkin We have a failing test

**Comment by georgiy-abbasov** [comment]
@inikulin, it's not relate to PR, i am working on it

**Comment by inikulin** [comment]
@georgiy-abbasov So it's a real fail and we're blocked on it?

**Comment by georgiy-abbasov** [comment]
No, just fix the test

**Comment by AlexanderMoskovkin** [comment]
\retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Pull request merged**
