### PR TITLE
fix child window reloading, when child window is opened from iframe (closes #5930)

### LINKED ISSUE #5930: `Cannot switch to the window` after/while interacting with child window
### What is your Test Scenario?

We have a number of tests which interact with the PayPal window, multiple times.

Example flow:
1. Make a Payment using PayPal
2. Return to Payment page, and make a 2nd Payment
3. Interact with PayPal 3rd time
4. Confirm payment successful
 
### What is the Current behavior?

Although inconsistently, TestCafe often fails switching between windows; either the last step inside the paypal child window (click _confirm/continue_), or the 1st step after the window closes (_switching to the PayPal iFrame, to click again_): `Cannot switch to the window`.
For some reason the test for my demo app also fails with `A native alert dialog was invoked on page...` but that is unrelated since it's not happening on our actual tests.
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

If you check out my [testcafe_issues](https://github.com/rob4629/testcafe_issues) repo, you should just be able to use the test `Enter child window multiple times`
1. npm start -- starts the local server.
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 

```js
 fixture("Multiple Window Testing").page("localhost:4000")

const clickPayWithPaypal = async () => {
    const buttonIframe = Selector('#smart-button-container iframe');
    const payWithPaypalButton = Selector('[data-funding-source="paypal"]');

    await t
        .switchToIframe(buttonIframe)
        .expect(payWithPaypalButton.with({ visibilityCheck: true }).exists)
        .ok({ timeout: 40000 })
        .hover(payWithPaypalButton)
        .click(payWithPaypalButton)
        .switchToMainWindow();
}

const clickContinueButtonWithRetry = async () => {
    const acceptAllButton = Selector('#acceptAllButton');
    const continueButton = Selector('[data-testid="submit-button-initial"]');
    if (await acceptAllButton.visible) await t.click(acceptAllButton);
    await t.click(continueButton);
    if (await continueButton.visible) await t.click(continueButton);
  }

test("Enter child window multiple times", async () => {
    await clickPayWithPaypal();

    await t
      .typeText(Selector('#email'), <test-email>)
      .click(Selector('#btnNext'))
      .typeText(Selector('#password'), <test-password>)
      .click(Selector('#btnLogin'));
    await clickContinueButtonWithRetry();

    // Repeat
    await clickPayWithPaypal();
    await clickContinueButtonWithRetry();

    // Repeat
    await clickPayWithPaypal();
    await t.click(Selector('[data-testid="submit-button-initial"]')).wait(750);
});

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "assertionTimeout": 15000,
  "pageLoadTimeout": 30000,
  "selectorTimeout": 15000,

  "disableMultipleWindows": false,

  "quarantineMode": false,
  "skipJsErrors": true,

  "disablePageCaching": true,

  "reporter": [
    {
      "name": "xunit",
      "output": "artifacts/test-results/results.xml"
    },
    {
      "name": "spec"
    }
  ],

  "screenshots": {
    "fullPage": true,
    "takeOnFails": true,
    "pathPattern": "${TEST_ID}/${RUN_ID}_${FILE_INDEX}.png",
    "path": "artifacts/screenshots"
  }
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
 Enter child window multiple times (screenshots:
 /Users/rcooper/Personal/testcafe_issues/artifacts/screenshots/test-1/_errors/1.png)

   1) A native alert dialog was invoked on page "http://localhost:4000/", but no handler was set for it. Use the
      "setNativeDialogHandler" function to introduce a handler function for native dialogs.

      Browser: Chrome 88.0.4324.150 / macOS 10.15.7


   2) Cannot switch to the window.

      Browser: Chrome 88.0.4324.150 / macOS 10.15.7
      Screenshot: null

         22 |}
         23 |
         24 |const clickContinueButtonWithRetry = async () => {
         25 |    const acceptAllButton = Selector('#acceptAllButton');
         26 |    const continueButton = Selector('[data-testid="submit-button-initial"]');
       > 27 |    if (await acceptAllButton.visible) await t.click(acceptAllButton);
         28 |    await t.setNativeDialogHandler(() => true).click(continueButton);
         29 |    if (await continueButton.visible) await t.setNativeDialogHandler(() => true).click(continueButton);
         30 |  }
         31 |
         32 |test("Click link within iFrame to open window", async () => {

         at <anonymous> (/Users/rcooper/Personal/testcafe_issues/tests/multi_window_link.js:27:31)
         at asyncGeneratorStep (/Users/rcooper/Personal/testcafe_issues/tests/multi_window_link.js:1:231)
         at _next (/Users/rcooper/Personal/testcafe_issues/tests/multi_window_link.js:1:569)
         at <anonymous> (/Users/rcooper/Personal/testcafe_issues/tests/multi_window_link.js:1:734)
         at <anonymous> (/Users/rcooper/Personal/testcafe_issues/tests/multi_window_link.js:1:475)
         at clickContinueButtonWithRetry (/Users/rcooper/Personal/testcafe_issues/tests/multi_window_link.js:24:35)
         at <anonymous> (/Users/rcooper/Personal/testcafe_issues/tests/multi_window_link.js:58:11)
         at asyncGeneratorStep (/Users/rcooper/Personal/testcafe_issues/tests/multi_window_link.js:1:231)
         at _next (/Users/rcooper/Personal/testcafe_issues/tests/multi_window_link.js:1:569)


 1/1 failed (45s)
npm ERR! Test failed.  See above for more details.
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Check out my demo repo
2. Start the server (`npm start`)
3. Open a new console and run the `Enter child window multiple times` test
4. See the error...
 
### Your Environment details:
 
* testcafe version: 1.10.0-rc.4 > 1.10.2-alpha.2                  
* node.js version: 12.14.3                   
* command-line arguments:  
* browser name and version: Chrome 87 
* platform and version: Mac OS  
* other:

### PR DESCRIPTION
**Pull request by AlexKamaev**
Prevent duplicating child link if the child window is opened and reloaded in iframe

### CODE REVIEW

**Comment by rob4629** [comment]
I've tested this change locally, and only experienced the error `Cannot switch to the window` once (_out of 20-30 runs_). That's far better from consistently seeing it.
Happy to run through further tests and give you feedback (if you're planning on making more changes to this PR)

**Review by Farfurix — APPROVED** [review]

**Comment by AlexKamaev** [comment]
@rob4629 

Thank you for your feedback. At this moment, I would merge this PR (after v11.0 is released) as is since I'm sure that it fixes some issues with iframes and child windows. As for other issues, I would really appreciate it if you test your scenarios again and try to reproduce your issues consistently.

**Review by miherlosev — APPROVED** [review]

**Comment by AlexKamaev** [comment]
@testcafe-build-bot re

**Comment by rob4629** [comment]
> At this moment, I would merge this PR (after v11.0 is released)

So... no chance of having this released _with_ `1.11.0`?? 😂 . No worries, I appreciate how quickly you were able to look at, and resolve this issue for me!

**Pull request merged**
