### PR TITLE
Fix the cors check

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

**Review by miherlosev — APPROVED** [review]

**Review by Farfurix — APPROVED** [review]

**Review by AndreyBelym — APPROVED** [review]
It's good, but please use draft PRs when using pre-release dependencies

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

**Review by AndreyBelym — APPROVED** [review]

**Pull request merged**
