### PR TITLE
[docs] Support the mobile landing

### PR DESCRIPTION
**Pull request by VasilyStrelyaev**
\cc @DevExpress/testcafe-docs 

The main repository part of mobile landing.

http://strelyaev-w8:8080/testcafe/

### CODE REVIEW

**Comment by helen-dikareva** [comment]
Look at the line (on ipad event without cookie note)
image

**Comment by helen-dikareva** [comment]
Bottom part looks broken on ipad 
image

**Comment by helen-dikareva** [comment]
On my phone (Samsung Galaxy S5) I cann't scroll to the `TestCafe Studio` item in the menu in horizontal orientation. On simulator I can because there is not top part with url address.

**Comment by VasilyStrelyaev** [comment]
> Move testcafe-live-promo div in features div, because now there is extra indent

Why not just remove the indent? I'm tired of moving things specially for the mobile version - hate extra js.

**Comment by VasilyStrelyaev** [comment]
> Bottom part looks broken on ipad

Do you mean only the Twitter/GitHub part or the Studio promo too (the screenshot)?

**Comment by VasilyStrelyaev** [comment]
> Look at the line (on ipad event without cookie note)

Isn't it a browser artifact? It appears only when you zoom - and it doesn't appear at 100%.
Or you think the reason is in CSS?

**Comment by helen-dikareva** [comment]
I'll reply in private

**Comment by AndreyBelym** [comment]
@testcafe-build-bot retest

**Comment by VasilyStrelyaev** [comment]
@testcafe-build-bot \retest

**Pull request merged**
