### PR TITLE
Disable spinner in CI environments (closes #733)

### LINKED ISSUE #733: elegant-spinner does not work well on Travis CI
See https://travis-ci.org/DevExpress/testcafe-browser-provider-saucelabs/jobs/153545421

### PR DESCRIPTION
**Pull request by AndreyBelym**
\сс @inikulin @AlexanderMoskovkin @VasilyStrelyaev

### CODE REVIEW

**Comment by inikulin** [comment]
BTW, can you condirm it works well on Travis?

**Comment by AndreyBelym** [comment]
Yep: https://travis-ci.org/DevExpress/testcafe-browser-provider-saucelabs/jobs/153573126, https://travis-ci.org/DevExpress/testcafe-browser-provider-saucelabs/jobs/153573127

**Comment by inikulin** [comment]
Why it writes "undefined" in output before error message in provided logs? Is this somehow related?

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by AndreyBelym** [comment]
Nope, "undefined" belongs to provider debugging (In more words, it tries to print out the secret environment var SAUCE_USERNAME, but fails, because Travis CI doesn't pass secrets to pull requests).

**Comment by inikulin** [comment]
lgtm then

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
