### PR TITLE
[docs] Fix a request logger example

### PR DESCRIPTION
**Pull request by VasilyStrelyaev**
\cc @DevExpress/testcafe-docs @miherlosev

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
A question to @miherlosev and @kirovboris:
To access the `logger.requests` property, we must wait for the request to happen, and, since we don't have `waitFor`, the only way to do this is to write an assertion.

Don't you think that something is not okay with this? Write an assertion just to wait...

**Comment by miherlosev** [comment]
> Don't you think that something is not okay with this? Write an assertion just to wait...

I agree with you that it is not clear. Sometime we see customer cases when custom waiting is necessary. In this case we suggest assertion or `wait` methods. I propose to create proposal for `waitFor (predicate)`.

**Comment by VasilyStrelyaev** [comment]
Discussed with @kirovboris in private. He said we should **not** introduce `waitFor` again. Since it's obvious that waiting via an assertion is awkward, I'll change the comment to remove words about *waiting* and pretend that this is a regular use of assertion. @kirovboris said that this example is synthetic, not a valid user scenario.

When we learn about real use cases when custom waiting is necessary, we'll continue the discussion.

**Comment by VasilyStrelyaev** [comment]
@testcafe-build-bot \retest

**Pull request merged**
