### PR TITLE
Gulpfile - Fix website build on macOS

### PR DESCRIPTION
**Pull request by VasilyStrelyaev**
A new `env` object without parent's `process.env` was passed to Jekyll and overrode its environment.
The build somehow worked on Windows all these years, but not on macOS.
This PR fixes it.

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
@testcafe-build-bot \retest

**Comment by kirovboris** [comment]
@testcafe-build-bot \retest

**Comment by VasilyStrelyaev** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
`testcafe-build-bot` doesn't work with Azure

**Pull request merged**
