### PR TITLE
RAW api iframe switching test added (closes #602)

### LINKED ISSUE #602: We need RAW API functional tests for iframe switching

### PR DESCRIPTION
**Pull request by helen-dikareva**
/cc @AlexanderMoskovkin @georgiy-abbasov

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
ping @georgiy-abbasov

**Comment by georgiy-abbasov** [comment]
\r- Just few minor remarks, i explained in private

**Comment by AlexanderMoskovkin** [comment]
it's better to publish them here in the next time

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by AndreyBelym** [comment]
lgtm

**Pull request merged**
