### PR TITLE
Switch to Babel 6 (fixes #265)

### LINKED ISSUE #265: Switch to Babel 6
Surprises :tada: :

- [x] Runtime is inserted in the client code despite the `.babelrc` settings. 
**Solved:**  The issue was caused by the fact that we disabled runtime only in the `src/client`. `pinkie` module required from `node_modules` so it's used global config instead of  the `src/client/babelrc` (for some reason it's worked fine in babel5). The solution is to move config to `src`, so `node_modules` will not be compiled at all.

- [x] es6-modules plugin now always inserts `'use strict'` which doesn't work for us (see #258)

- [x] Incorrect hoisting of tagged template literals  (~~bug reported: https://phabricator.babeljs.io/T6961~~, there is a PR already: https://github.com/babel/babel/pull/3118). ~~Temporary workaround: remove `transform-runtime` and add `babel-plugin-transform-regenerator`~~ (won't work :cry: ). Just getting rid of tagged string literals for now :sob: 

- [x] `export default` semantics change. You need specify `default` explicitly if you require ES6 code from ES5 (https://www.npmjs.com/package/babel-plugin-add-module-exports should do a trick)

### PR DESCRIPTION
**Pull request by inikulin**
\cc @AlexanderMoskovkin @churkin 
You can read about motivation on changes in #265

### CODE REVIEW

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
We have to do something with this tests.. We'll try to fix this

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
Tests pass now

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
ping @churkin

**Comment by churkin** [comment]
lgtm

**Pull request merged**
