### PR TITLE
update testcafe version

### PR DESCRIPTION
**Pull request by helen-dikareva**
/cc @inikulin @AlexanderMoskovkin 
We have breaking change in https://github.com/DevExpress/testcafe/issues/650

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
I have a couple of late thoughts about https://github.com/DevExpress/testcafe/issues/650

@helen-dikareva said I'd better post them here

so, we have `test{num}` in the screenshot path, e.g. `test-1`, `test-2`, ...
if the test is quarantined, we use `test{num}{run}`, e.g. `test-1-1`, `test-1-2`, ...

One may think we are talking about tests number `1.1`, `1.2`, ...

I'd add some descriptive word like `test-1-run-1`, `test-1-run-2`, ...

What do you think?

**Comment by churkin** [comment]
May be `attempt`?

**Comment by VasilyStrelyaev** [comment]
Nope, these are not attempts. Attempts is something we expect to either succeed or fail. From the point of view of testing framework, all runs are successful - we have determined the test status - failed or passed.

**Comment by helen-dikareva** [comment]
@inikulin so what do think about @VasilyStrelyaev comment https://github.com/DevExpress/testcafe/pull/732#issuecomment-241020421 ?

**Comment by inikulin** [comment]
first of all we can't use different test-N dirs, which one you will specify in report? This is the only thing I care about here. Once you'll find how to deal with it - everything else will be just fine

**Comment by AlexanderMoskovkin** [comment]
lgtm
@inikulin let's merge this?

**Pull request merged**
