### PR TITLE
Double click command (#441)

### PR DESCRIPTION
**Pull request by helen-dikareva**
\cc @AlexanderMoskovkin @AndreyBelym

### CODE REVIEW

**Comment by AndreyBelym** [comment]
lgtm

**Comment by helen-dikareva** [comment]
ping @AlexanderMoskovkin

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by helen-dikareva** [comment]
\cc @VasilyStrelyaev

**Comment by VasilyStrelyaev** [comment]
lgtm

**Pull request merged**
