### PR TITLE
Fixed upload method for correct displaying file names in error message (closes #336)

### LINKED ISSUE #336: Incorrect error message while uploading non-existing files.
Before now, when we tried to upload non-existing files, their names figured in error message.
For now, name for invalid file replaces with null.
[Error message](http://content.screencast.com/users/GeorgeZA/folders/Jing/media/c4acb238-68be-4dba-94c6-6790946aef19/2016-02-09_1358.png)

### PR DESCRIPTION
**Pull request by georgiy-abbasov**
\cc @AlexanderMoskovkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
@georgiy-abbasov I suppose we will add a test for this in the context of the https://github.com/DevExpress/testcafe/issues/293 issue?

**Comment by georgiy-abbasov** [comment]
@AlexanderMoskovkin, yes, they will be added with pull-request for this task (#293)

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
