### PR TITLE
Use writeFileSync in the 'update-greenkeeper' gulp task (closes #315)

### LINKED ISSUE #315: Unexpected end of input error appears during the `gulp build` task
Sometimes the following error appears when the `gulp build` task is running:
```
SyntaxError: Cannot read config file: c:\Work\Git\testcafe-phoenix\package.json
Error: c:\Work\Git\testcafe-phoenix\package.json: Unexpected end of input
```

This appears when the `lint` task reads the `package.json` file while the `update-greenkeeper` task is rewriting it. 
I propose to use the `fs.writeFileSync` method instead of async version in the `update-greenkeeper` task to avoid this problem and possible collisions with some other task

### PR DESCRIPTION
**Pull request by AlexanderMoskovkin**
/cc @inikulin

### CODE REVIEW

**Comment by inikulin** [comment]
We need a comment why we do it. So we will not accidentally rewrite it back to async version.
\r-

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
thanks

**Pull request merged**
