### PR TITLE
[docs] Landing page modified

### PR DESCRIPTION
**Pull request by MargaritaLoseva**
The text has been changed due to Armina comments.
@inikulin @VasilyStrelyaev Please, check if this new text is correct technically. Then I'll send it to Armina again.

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
I'll add [WIP] if you don't mind

**Comment by VasilyStrelyaev** [comment]
hang tight, I'm rewriting it all a bit

**Comment by VasilyStrelyaev** [comment]
4 hours left until it's [semi]automatically merged

**Comment by VasilyStrelyaev** [comment]
@MargaritaLoseva  Armina didn't respond so let's leave it as it is. I'll change this `dozens of` thing as soon as Armina replies.

**Comment by MargaritaLoseva** [comment]
\cc @DevExpress/testcafe

**Comment by VasilyStrelyaev** [comment]
Oh, I can push here it turns out - there was no reason to hurry up.
So, we'll wait for Armina to respond.

**Comment by VasilyStrelyaev** [comment]
\cc @DevExpress/testcafe-docs

**Comment by VasilyStrelyaev** [comment]
@DevExpress/testcafe-docs do we have to remove PhantomJS from the docs as well?

I think it's connected to whether we remove the plugin from npm... Or it's not?

**Comment by AlexanderMoskovkin** [comment]
>  do we have to remove PhantomJS from the docs as well?

I suppose, yes. 

> whether we are going to remove the plugin from npm

I don't see a connection there. The `testcafe-browser-provider-phantomjs` module works ok, there are no reason to remove it. But there are problems with tests running in phantomjs. We just should not tell that we are supporting phantomjs while it doesn't work actually

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by VasilyStrelyaev** [comment]
We'll be having a new landing page design soon

http://take.ms/Ei8a5

And it requires just one little `<br/>` in this repo.

I don't really want to make a separate PR - let it be here (this PR is already a dump)

**Comment by VasilyStrelyaev** [comment]
\cc @churkin

**Pull request merged**
