### PR TITLE
Implemented Hybrid function initialization errors (#241)

### PR DESCRIPTION
**Pull request by inikulin**
\cc @helen-dikareva @AlexanderMoskovkin 
@VasilyStrelyaev please, check strings

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by helen-dikareva** [comment]
lgtm

**Comment by inikulin** [comment]
ping @AlexanderMoskovkin

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
