### PR TITLE
Use body.clientWidth/Height if document is in compat mode (closes #883)

### LINKED ISSUE #883: Strange 'Element is not visible' error
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Error 'Element is not visible' is shown when clicking on second div.

### What is the expected behavior?
Scroll to the second div and click on it.

### How would you reproduce the current behavior (if this is a bug)?
Run the test

#### Provide the test code and the tested page URL (if applicable)

Tested page:
```html
<html>
<head>
<title></title>
</head>
<body>
<style>
    .child1 {
        height: 900px;
    }
    .child2 {
        height: 200px;
    }
</style>
    <div class="child1">Span1</div>
    <div class="child2">Span2</div>
</body>
</html>
```
Test code

```js
fixture `123`.page `belym-w8:8080`

test('test', async t => {
    await t
        .click('body > div:nth-child(2)')
        .click('body > div:nth-child(3)');
});
```

### Specify your

* operating system: Windows 10
* testcafe version: 0.9.0-rc2
* node.js version: 6.5.0

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @AlexanderMoskovkin @georgiy-abbasov

### CODE REVIEW

**Comment by georgiy-abbasov** [comment]
@AndreyBelym, can we add the test for this behavior ?

**Comment by AndreyBelym** [comment]
The test is here: https://github.com/AlexanderMoskovkin/stored-functional-tests/blob/master/tests/scroll/scroll.test.js#L105

**Comment by AlexanderMoskovkin** [comment]
@AndreyBelym add the test here (you can use `act.hover` for example). We should add a regression test for each fix.
These stored tests will be reworked and added later when we will implement act.scroll

**Pull request merged**
