### PR TITLE
Declare that error happens during tests preparation for the API globals errors

### PR DESCRIPTION
**Pull request by inikulin**
\cc @AlexanderMoskovkin @AndreyBelym

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
\cc @AndreyBelym

**Comment by AndreyBelym** [comment]
lgtm

**Pull request merged**
