### PR TITLE
Add reportTestStart method to reporting system (close #3715)

### LINKED ISSUE #3715: Update ReporterPluginHost class with reportTestStart
### What is your Test Scenario?
```
test('Test 1', async (t) => {
    await app.goRoot();
    await app.waitLoading();
    await allure.createStep('Check Help', async () => {
        await app.header.click('helpIcon');
        const title = await app.getPageTitle();
        await t.expect(title).eql('Docketing Portal');
    })();
});
```
### What are you suggesting?
IReporterPluginHost has just method reportTestDone and doesn't have reportTestStart method so we don,t have ability to add something between test start and finish. 
Fore example: it is impossible to add allure steps to tests which is very useful for e2e testing.
I suggest to add method for starting and finishing of test instead of handling all information in reportTestDone

### PR DESCRIPTION
**Pull request by Ivan-Katovich**
To work correctly with such reporters as Allure and have ability to add something to report during current test execution process I added reportTestStart method to reporting system 
Related feature request: https://github.com/DevExpress/testcafe/issues/3715

### CODE REVIEW

**Comment by Ivan-Katovich** [comment]
"continuous-integration/travis-ci/push" these tests fails in different places, which are not related with my fix, could somebody rerun this check  ?

**Comment by Ivan-Katovich** [comment]
- I added tests for reportTestStart 
 - I checked that all events for test-run-start return a promise or are used with await word. 
 - I added check that reportTestDone is in reporter plugin.

**Comment by Ivan-Katovich** [comment]
I missed something in tests but I can't understand what it is. 
Could somebody help me with that ?

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Comment by Ivan-Katovich** [comment]
@testcafe-build-bot retest

**Comment by Ivan-Katovich** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@AndreyBelym FPR

**Pull request merged**
