### PR TITLE
Address #6624, adding 'new' keyword to page-unload-barrier Promise

### PR DESCRIPTION
**Pull request by rob4629**
## Purpose
_Describe the problem you want to address or the feature you want to implement._
Address https://github.com/DevExpress/testcafe/issues/6624, where exception is thrown as detailed by @danieltroger [here](https://github.com/DevExpress/testcafe/issues/6624#issuecomment-975918371). 

## Approach
_Describe how your changes address the issue or implement the desired functionality in as much detail as possible._
Add `new` keyword to Promise creation, for `waitForFileDownload` in [page-unload-barrier.ts](https://github.com/DevExpress/testcafe/blob/master/src/client/core/barriers/page-unload-barrier.ts#L68-L78)

## References
_Provide a link to the existing issue(s), if any._

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

### CODE REVIEW

**Comment by Farfurix** [comment]
@rob4629 

Thank you for your contribution to TestCafe. We will review this PR.

**Comment by rob4629** [comment]
I didn't add any new tests, as I felt this change would be covered by `test/client/fixtures/core/page-unload-barrier.js`

**Comment by rob4629** [comment]
> Check it in context of #6736

👋🏻 @miherlosev, was this comment for me? I've tried updating the Safari version in `test/function/config.js` but not really sure what Safari tests need to be updated.

**Comment by miherlosev** [comment]
Hi @rob4629,

It was a comment for the team members. We can merge this PR and release a new alpha version if you need a version with the fix faster.

**Comment by rob4629** [comment]
Thanks for the offer. I'm good to wait until the next planned release

**Comment by danieltroger** [comment]
Same, the yarn patch I made still works 👍

**Review by AndreyBelym — APPROVED** [review]

**Pull request merged**
