### PR TITLE
iframe driver initialization fixed (closes #1154)

### LINKED ISSUE #1154: TD - 0.12.0 - Test stalls on second or third time
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

Test stalls 

### What is the expected behavior?

Test should work

### How would you reproduce the current behavior (if this is a bug)?

run test several times

#### Provide the test code and the tested page URL (if applicable)
```js
import { Selector, ClientFunction } from 'testcafe';

fixture("TD 0.12.0 FIRST")
    .page `https://jqueryui.com/selectable/#serialize`;

test('Test1', async t => {
    await t
        .switchToIframe('iframe')
        .click('#selectable > li:nth-child(2)')
        .click('#selectable > li:nth-child(5)', { modifiers: { ctrl: true } })
        .expect(Selector('#selectable > li:nth-child(2)').hasClass('ui-selected')).ok()
        .expect(Selector('#selectable > li:nth-child(5)').hasClass('ui-selected')).ok();
});

test('Test2', async t => {
    await t
        .switchToIframe('iframe')
        .click('#selectable > li:nth-child(2)')
        .click('#selectable > li:nth-child(5)', { modifiers: { ctrl: true } })
        .expect(Selector('#selectable > li:nth-child(2)').hasClass('ui-selected')).ok()
        .expect(Selector('#selectable > li:nth-child(5)').hasClass('ui-selected')).ok();
});

```

### Specify your

* operating system: win10
* testcafe version: 0.12.0
* node.js version: 4.4.7

### PR DESCRIPTION
**Pull request by georgiy-abbasov**

### CODE REVIEW

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot

**Comment by georgiy-abbasov** [comment]
As i expected, gh-1154 test crashes TestCafe without fix - [link](https://travis-ci.org/testcafe-build-bot/testcafe/jobs/200320045#L363)

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
\cc @AlexanderMoskovkin

**Comment by AlexanderMoskovkin** [comment]
it's discussed with @georgiy-abbasov in private. We need to rethink this

**Comment by georgiy-abbasov** [comment]
We should come up with another approach, i will reopen when it will be ready

**Pull request closed without merging**
