### PR TITLE
[docs] Add an announcement blog post for v0.22.0

### PR DESCRIPTION
**Pull request by VasilyStrelyaev**
\cc @DevExpress/testcafe-docs

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
Ignore the tests - this link will be valid when we update the website

**Comment by VasilyStrelyaev** [comment]
> When an incorrect call occurs in a chain of selector methods, the test run report now identifies the exact method that failed to match any DOM element.

@churkin didn't like `incorrect call` in this phrase. I also have doubts regarding this part. Do you think it's okay?

**Comment by helen-dikareva** [comment]
I don't like it neither.
We can say it simpler, e.g:
`Now the test run report can identifies which selector's method failed to match any DOM element.`
I think it is obvious that it is `in case if selector does not match any element in the DOM tree`.

**Comment by VasilyStrelyaev** [comment]
Dirk is on sick leave, but I still hope that someone could check this piece. So please don't merge until, say, 16:00.

**Comment by VasilyStrelyaev** [comment]
You are free to merge it now (regardless of the tests).

**Pull request merged**
