### PR TITLE
Implement plugin system for the reporters (closes #196):

### LINKED ISSUE #27: Create gulp-publish task
The task should build sources before publishing and ensure that the NPM user is logged as `devexpress`. Then it should execute `npm publish`. It can perform additional checks, e.g. what CHANGELOG is updated, latest travis build is passing, etc.

### LINKED ISSUE #196: Implement report plugins system
As we (with @inikulin) discussed before `xunit` and `nunit` reports have the differences. So we should implement the `nunit` reporter

### PR DESCRIPTION
**Pull request by inikulin**
- Moved reporters to the individual plugin packages
- Implemented reporter Yeoman generator
- Added gulp publish task (closes #27)

\cc @AlexanderMoskovkin @kirovboris @churkin @VasilyStrelyaev

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by kirovboris** [comment]
lgtm

**Comment by inikulin** [comment]
ping @churkin

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by churkin** [comment]
lgtm

**Pull request merged**
