### PR TITLE
Add ability to get skipped tests when using getTestList for static analysis

### PR DESCRIPTION
**Pull request by flora8984461**
## Purpose
_Describe the problem you want to address or the feature you want to implement._

I have opened an issue https://github.com/DevExpress/testcafe/issues/6238, and I was suggested to open a PR. The purpose is to add property of "isSkipped" when using getTypeScriptTestList / getTypeScriptTestListFromCode and getTestList / getTestListFromCode when I just want to do a static analysis without actually running the tests.

## Approach
_Describe how your changes address the issue or implement the desired functionality in as much detail as possible._

1) Add property "isSkipped" in Class Fixture, Class Test and formatFnData().
2) Add check if the test / fixture is skipped by a new function getSkippedInfo().
3) Pass the isSkipped property in analyze() for fixture and test.

## References
_Provide a link to the existing issue(s), if any._

https://github.com/DevExpress/testcafe/issues/6238

## Pre-Merge TODO

I think the test "src/compiler/test-file/test-file-parser-base.js" includes the test I need, and I made the required updates.
I have run the following tests on my local,
```
gulp test-server - all pass, except for some existing "errored after" from the master branch
gulp test-functional-local - some screenshots not stable pass, and encounter `Error: Port 1337 is occupied by another process.` which exists in master branch
gulp test-client-local - there seem to be some existing failure from the master branch
```
And I found the link on Contributing Guide https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/reference/command-line-interface.md#file-pathglob-pattern and https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/reference/command-line-interface.md cannot be reached now.

I am opening PR for review to double-check if I am missing anything and looking for feedback on my approach. Thank you so much!

- [x] Write tests for your proposed changes
- [x] Make sure that existing tests do not fail
marking this since the tests including my changes have passed. 

Hi @AlexSkorkin @AlexKamaev @miherlosev Would you mind helping review and approve running workflows? Thanks! I cannot add reviewers.

### CODE REVIEW

**Comment by miherlosev** [comment]
Hi @flora8984461 
Thank you for contributing to TestCafe. We will review this PR.

Also I fixed the broken links in the [Contribution guide](https://github.com/DevExpress/testcafe/blob/master/CONTRIBUTING.md) page.

**Comment by AlexKamaev** [comment]
It seems that the PR is not finished yet.
I reviewed the following test:


```JS
it('Hooks in test file', function () {
        const expectedStructure = [
            [
                new Fixture('fixture1', 0, 23, new Loc(1, 0, 1, 23), {},
                    [
                        new Test('fixture1test1', 26, 111, new Loc(3, 0, 9, 2), {}),
                    ]
                ),
               ...
            ],
        ];
        
        return testJSFilesParser('./data/test-suites/fixture-and-test-hooks', expectedStructure);
```
And alsoI had a look at the testfile:
```JS
fixture `fixture1`.skip;
    test.before(async t => {
})
('fixture1test1', async t => {
}).after(async t => {
});
```
In the test file, fixture1 is skipped. However, in the test it is not skipped, and the test passes. This means that the test is incorrect. But the test passes - this means that the parser does not work correctly with this usage scenario.

Please take a look at other tests. There may be similar cases as well. We can merge this PR only if we are sure that all cases are covered.

**Comment by flora8984461** [comment]
Thank you so much for your review. I will update my PR soon.

**Comment by flora8984461** [comment]
Still have some issue with typescript's get-test-list, working on it...

**Comment by flora8984461** [comment]
Hi @AlexKamaev , thank you so much for helping review, I found some miss. I made the fix and added several new test cases in the testfile in fixture-and-test-hooks. Would you mind helping review again? I wonder if there is any better way to do it and if there are any other cases I can consider testing. Thanks!

**Comment by AlexKamaev** [comment]
@flora8984461
I checked your approach. I'm afraid it does not look reliable. I found one more case when the `skip` property is not applied:
```JS
fixture
    .beforeEach(async t => {})
    .before(async t => {})
    ('fixture5');

test
    .skip // <-------------------------------------
    .before(async t => {})
    .after(async t => {})
    `fixture5test1`
```

I would like to see one special method that will detect if the `skip` is applied instead of putting a lot of `currentSkip = true` expressions in different places of code. Unfortunately, I cannot give you more detailed recommendations on this PR.

**Comment by flora8984461** [comment]
Thanks for your feedback. I think I might need more time to make it a better way.  I prefer one special method that will detect if the skip is applied too. Let me convert it to draft and work on it more.

**Comment by flora8984461** [comment]
Hi, @AlexKamaev  
I updated my method to use one function to get all skipped cases and updated tests. 

Thanks for your patience and your time to review!

**Comment by AlexKamaev** [comment]
I'll check the PR a little later.

I checked #6433. It's not related to your changes

**Review by AndreyBelym — APPROVED** [review]

**Comment by AndreyBelym** [comment]
LGTM but should be rebased and merged only after the patch release.

**Review by AlexKamaev — APPROVED** [review]

**Comment by flora8984461** [comment]
@AlexKamaev @AndreyBelym 

Thank you so much for your time and for helping me refractory. I will do the rebase, or do you prefer doing it?

And when is the patch release?

**Comment by AlexKamaev** [comment]
@flora8984461 I do not have enough permissions to do rebase in your branch. If you grant me permissions, I can do the rebase, or you can do it yourself. At present, we cannot give you precise estimation about the next release date.

**Comment by flora8984461** [comment]
@AlexKamaev Thanks, sorry I forgot about the access. I did a rebase and sent you an invite as a collaborator on my forked branch (I think that can grant rebase access?) just in case there will be more need updates / rebase.

**Pull request merged**
