### PR TITLE
Redesign test run errors (#685 part1)

### PR DESCRIPTION
**Pull request by inikulin**
\cc @AlexanderMoskovkin @churkin @kirovboris @VasilyStrelyaev

### CODE REVIEW

**Comment by kirovboris** [comment]
lgtm

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
Guys, how do you even review? I've accidentally removed all changes and no one mentioned (((

**Comment by AlexanderMoskovkin** [comment]
I missed this. But I saw the changes in the tests, so they should be failed if something went wrong with source changes.

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by kirovboris** [comment]
lgtm

**Comment by churkin** [comment]
lgtm

**Pull request merged**
