### PR TITLE
incorrect testing time calculation for xunit and json reporters fixed (сloses #1674)

### PR DESCRIPTION
**Pull request by helen-dikareva**
waiting for 3.1.1 version of testcafe-lagacy-api

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
There are a linting errors, fix'em please

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
Yep, it's a cool feature from GitHub

**Pull request merged**
