### PR TITLE
fix ASPxperienceDemos (close #395)

### LINKED ISSUE #395: Fix ASPxperienceDemos tests after merge clickAutomation refactoring

### PR DESCRIPTION
**Pull request by helen-dikareva**
For fix tests I just replaced (https://github.com/DevExpress/testcafe/pull/396/files#diff-27aea5773c389e89e84c3a8e9953640dR448)
```
new iframe.contentWindow[automation.AUTOMATION_RUNNERS].ClickAutomation(element, clickOptions) :
```
to
```
new iframe.contentWindow[AUTOMATIONS].ClickAutomation(element, clickOptions) :
```

I didn't refactor actions.js, but I added this file in 'lint-client' and fixed all ESlint error in it.
\cc @AlexanderMoskovkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
lgtm
Can merge after tests are succeed

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
@AlexanderMoskovkin  Can we leave version without fix ESLint errors in this PR?

**Comment by AlexanderMoskovkin** [comment]
Yes, we can. We should fix the tests first. Is this ok now?

**Comment by helen-dikareva** [comment]
Yes, I checked it on our CC task 'TESTCafe ASPxperienceDemos tests - Get Rid Of JQuery '

**Comment by AlexanderMoskovkin** [comment]
lgtm then

**Pull request merged**
