### PR TITLE
Fix status panel for Mac (closes #3631)

### LINKED ISSUE #3631: 'Unlock Page' button markup broken on Mac
image
Look at [a historical condition](https://github.com/DevExpress/testcafe/blob/ea330eaf733bdf1439fb275e7d854767a5e4d453/src/client/ui/status-bar/index.js#L154). 
We likely should get rid of it and check that all is ok in all browsers on Mac.

### PR DESCRIPTION
**Pull request by AndreyBelym**
Closes #3631.

### CODE REVIEW

**Comment by AndreyBelym** [comment]
Screen Shot 2019-04-02 at 5 24 01 PM
Screen Shot 2019-04-02 at 5 24 45 PM
Screen Shot 2019-04-02 at 5 25 29 PM

**Comment by AndreyBelym** [comment]
\cc @helen-dikareva @VasilyStrelyaev

**Comment by helen-dikareva** [comment]
Is TestCafe's logo on screenshot for Firefox a part of a page? Or what is it

**Comment by AndreyBelym** [comment]
Nope, it's just the Studio icon from the Dock, it's not on the page.

**Pull request merged**
