### PR TITLE
Implement `Selector` (#574 part2) 

### PR DESCRIPTION
**Pull request by inikulin**
In this part:
- Implemented cross-browser (kinda) `innerText` in snapshots
- Introduce client function factories
- Adjust error messages with client function instantiation callsite
- Completely get rid of "hybrid" term in code
- Allows `Selector` accept string on construction

\cc @helen-dikareva @AlexanderMoskovkin @VasilyStrelyaev

### CODE REVIEW

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
What happened to client tests? Why they are so unstable again?

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
I like it, lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by VasilyStrelyaev** [comment]
lgtm

**Pull request merged**
