### PR TITLE
[WIP] Functional tests in MS Edge

### PR DESCRIPTION
**Pull request by AlexanderMoskovkin**

### CODE REVIEW

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@AlexanderMoskovkin OK, we have stable fails with upload test. Can we now keep only failing upload test and iframe tests that failed (not whole fixture). Also, disable Appveyor builds by rmoving .appveyor.yml and rebase on top of fix for innertext. Once we'll have tests isolated we can try to debug what's actually going on

**Comment by inikulin** [comment]
Interesting, seems like preceding test affects results. Can you enable preceding tests as well?

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Pull request closed without merging**
