### PR TITLE
[docs] Corrections

### PR DESCRIPTION
**Pull request by VasilyStrelyaev**
\cc @DevExpress/testcafe-docs 

*My* topics corrected by Armina and rewritten by me in some parts.

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
Oh, it also adds a tagline to the front page, but I think that's okay

**Comment by VasilyStrelyaev** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
lgtm

**Comment by kirovboris** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
