### PR TITLE
Split functional tests (`fixtures` and `legacy-fixtures`) - part 1 of #617

### PR DESCRIPTION
**Pull request by AlexanderMoskovkin**

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
I've splitted functional tests fixtures to two dirs: `fixtures`, `legacy-fixtures`
This PR is huge but in fact you can look just at the new tests structure
/cc @inikulin

**Comment by inikulin** [comment]
@AlexanderMoskovkin  I can't find functional tests from `api/legacy`, can you point me there are they now?

**Comment by AlexanderMoskovkin** [comment]
> I can't find functional tests from api/legacy

FPR
I've restored them. But we have just several tests for `click` there. We committed them when we were implementing functional harness to demonstrate how we should write the tests. And one nore test was added later as a regression test.
The most of legacy functionality is tested in client tests for now

**Comment by inikulin** [comment]
lgtm

**Comment by inikulin** [comment]
@AlexanderMoskovkin We will not merge it now, right? It will significantly slow down test runs.

**Comment by AlexanderMoskovkin** [comment]
I'd like to merge it now and don't keep so much uncommitted changes.
This will not slow down test runs, let me explain:

how it was:
```js
test-functional task: -start---setup environment---wait for free saucelabs vm---run tests(new+legacy)---tear down
```

how it is now:
```js
two tasks run in parallel:
test-functional: -------start---setup environment---wait for free saucelabs vm---run tests(new)--tear down
test-functional-legacy:-start---setup environment---wait for free saucelabs vm-------------------run tests(legacy)---tear down
```

For example,
[before](https://travis-ci.org/testcafe-build-bot/testcafe/builds/140479882) - 23 min 49 sec
[now](https://travis-ci.org/testcafe-build-bot/testcafe/builds/140503236) - 24 min 21 sec

**Pull request merged**
