### PR TITLE
Refactor async server tests that uses Promises (closes #208)

### LINKED ISSUE #208: Refactor async server tests that uses Promises
Mocha supports promises out of the box now, so you can write:
```js
it('smthg', function() {
    return somePromise()
              .then(function() {
                  // some assertions
               });
});
```
instead of:
```js
it('smthg', function(done) {
    return somePromise()
              .then(function() {
                  // some assertions
                  done();
               })
               .catch(done);
});
```

### PR DESCRIPTION
**Pull request by inikulin**
\cc @AlexanderMoskovkin @AndreyBelym

### CODE REVIEW

**Comment by inikulin** [comment]
FPR

**Comment by inikulin** [comment]
ping @AlexanderMoskovkin

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
While Andrey is not here, maybe @helen-dikareva could review this?

**Comment by helen-dikareva** [comment]
lgtm

**Comment by inikulin** [comment]
@helen-dikareva Thank you

**Pull request merged**
