### PR TITLE
[docs] Armina corrections

### PR DESCRIPTION
**Pull request by MargaritaLoseva**
\cc @DevExpress/testcafe-docs
My topics corrected by Armina.
And renaming:
Custom Reporter Plugin -> Reporter Plugin
Custom Browser Provider Plugin -> Browser Provider Plugin

### CODE REVIEW

**Comment by inikulin** [comment]
lgtm

**Comment by inikulin** [comment]
Weird that we don't have tests ran for this PR \cc @AlexanderMoskovkin @AndreyBelym

**Comment by inikulin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by kirovboris** [comment]
lgtm

**Pull request merged**
