### PR TITLE
fix browser restart (closes #3781)

### LINKED ISSUE #3781: Automatic Browser Restart (when frozen/hung) feature broken from v1.0.0 onwards
### What is your Test Scenario?

I wonder what happened to this feature this was first introduced in v0.23.0 - [Browsers are Automatically Restarted When They Stop Responding](https://devexpress.github.io/testcafe/blog/testcafe-v0-23-0-released.html#browsers-are-automatically-restarted-when-they-stop-responding-1815). This is an excellent feature and was working fine up until v0.23.3. When TestCafe v1.0.0 came out, this feature stopped working (even happens in v1.1.4). TestCafe won't restart the browser when it goes into hung/frozen state (Browser instances are open but no actions happen inside the browser window). I don't have 100% reproducible test to provide to reproduce this issue as TestCafe freezes for some unknown reasons. When we run in tests in Bamboo CI server, our jobs are getting stuck because TestCafe goes into hung state and we have to manually kill the job & shutdown all open browsers (see screenshot).

I would love to have this feature working back again. Can you guys take a look at the feature again and see why/where it might be broken? 
 
### What is the Current behavior?

When TestCafe encounters some strange issue, TestCafe freezes and stays frozen/hung state forever. It won't quit & restart the browsers and attempt to run the tests again.
 
### What is the Expected behavior?

If a browser stops responding while it executes tests, TestCafe restarts the browser and reruns the current test in a new browser instance. If the same problem occurs with this test two more times, the test run finishes and an error is thrown.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

f502bc

</details>

### Steps to Reproduce:

No exact 100% reproducible test script to provide to reproduce this issue.
 
### Your Environment details:
 
* testcafe version:                    Happens in v1.0.0, v1.1.0, v1.1.3 & latest v1.1.4 . Works fine in v0.23.3
* node.js version:                     v8.11.1
* command-line arguments:  
* browser name and version:  Chrome 74
* platform and version:           macOS 10.14
* other:

### PR DESCRIPTION
**Pull request by AlexKamaev**

### CODE REVIEW

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Comment by dcharan** [comment]
So from this feature I understand that If a browser stops responding while it executes tests, TestCafe restarts the browser and reruns the current test in a new browser instance. If the same problem occurs with this test two more times, the test run finishes and an error is thrown.

There is another problem occurring because of this issue:
Let say if you have which would take couple of minutes (couple of minutes because tests runs on cloud,  latency....) In the process of rerunning the test testcafe is hitting the limit of 5 minutes and throwing  error "**browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues."**

**Pull request merged**
