### PR TITLE
[docs] Replace 'ff' with 'firefox' in docs and tests data

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @inikulin @AlexanderMoskovkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
lgtm
/cc @VasilyStrelyaev

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by inikulin** [comment]
We need to prefix docs PRs with `[docs]` to run appropriate CI tasks on them

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot /retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
> We need to prefix docs PRs with [docs] to run appropriate CI tasks on them

I did it. Tests are ok.
lgtm

**Comment by AlexanderMoskovkin** [comment]
ping @inikulin

**Comment by AlexanderMoskovkin** [comment]
@AndreyBelym I suppose, you should rebase this according to the https://github.com/DevExpress/testcafe/pull/646#issue-164276276 comment

**Comment by AndreyBelym** [comment]
Rebased, please review.

**Comment by inikulin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
