### PR TITLE
Update hammerhead

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

**Comment by miherlosev** [comment]
Let's freeze testcafe and hammerhead until the next major will be released.

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
Since the release is delayed, I guess we can merge commits in a regular order.

**Review by miherlosev — APPROVED** [review]

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
Tasks are green (except continuous-integration-azure-desktop). https://github.com/DevExpress/testcafe/pull/5909#issuecomment-780644603
Task 'continuous-integration-azure-desktop' is green. https://github.com/DevExpress/testcafe/pull/5909#issuecomment-781145249

**Pull request merged**
