### PR TITLE
Separate client legacy code from the new one (part 1 of #673). Separate client tests (closes #617)

### LINKED ISSUE #617: Add more browsers for functional testing
At first we need to split old API and new API tests. And run tests for new API in all browsers. Also, maybe we could skip running client tests if code in `client` is not affected by PR?

### PR DESCRIPTION
**Pull request by AlexanderMoskovkin**
/cc @inikulin @helen-dikareva 

The pull request is really huge (it's because of client scripts and tests refactoring), so I'll explain what's going here.

Now we have the following client sub-modules:
```js
(./core) testCafeCore - base things and modules
(./automation) testCafeAutomation - automations and related utils
(./legacy) testCafeLegacyRunner - all legacy code (it was './runner' directory) - will be moved to a separate package
(./driver) testCafeDriver
(./ui) testCafeUI
```

Client tests were splitted to `fixtures` (`core` and `automation`) and `legacy-fixtures`. Legacy tests are run on our CCTray farm already. Now test scripts (except legacy) are checked by the `lint` task.

The most part of the PR is mechanical refactoring so during review you can look at the first commit (it's changes in `Gulpfile.js`) and maybe the second commit (it's `automation` sub-module).

### CODE REVIEW

**Comment by inikulin** [comment]
We need compound tasks now, so we can run things locally: run all client tests, run all functional tests.

**Comment by inikulin** [comment]
BTW, can you move legacy client code to `src/legacy/client`?

**Comment by AlexanderMoskovkin** [comment]
> BTW, can you move legacy client code to src/legacy/client?

The next step is move all legacy code to a separate package. Is there a reason to move legacy client code to anywhere now?

**Comment by inikulin** [comment]
Just thought it will simplify the process if we'll have all legacy related-stuff in one dir

**Comment by AlexanderMoskovkin** [comment]
ok

**Comment by AlexanderMoskovkin** [comment]
> BTW, can you move legacy client code to src/legacy/client?

done.

FPR

**Comment by AlexanderMoskovkin** [comment]
fpr

**Comment by inikulin** [comment]
lgtm

**Comment by helen-dikareva** [comment]
lgtm

**Pull request merged**
