### PR TITLE
Report should contain screenshot path if it was specified (closes #1269)

### LINKED ISSUE #1269: JSON reporter returns `screenshotPath: null` if a screenshot path is specified
### Are you requesting a feature or reporting a bug?

bug (created from a [discussion](https://testcafe-discuss.devexpress.com/t/why-json-reporter-returns-screenshotpath-null-when-i-specify-a-screenshot-path-in-cli/177)

### What is the current behavior?

`"screenshotPath": null`

### What is the expected behavior?

`"screenshotPath": "screenshots/..."`

### How would you reproduce the current behavior (if this is a bug)?

run `testcafe chrome test.js -S -s screenshots --reporter json`

#### Provide the test code and the tested page URL (if applicable)

any failed test

### Specify your
* testcafe version: 0.13.0

### PR DESCRIPTION
**Pull request by helen-dikareva**
/cc @AndreyBelym @inikulin

### CODE REVIEW

**Comment by inikulin** [comment]
Tests fail

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
FPR

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Pull request merged**
