### PR TITLE
prepared dev version to publish

### PR DESCRIPTION
**Pull request by miherlosev**
@AlexanderMoskovkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
I guess we should update `testcafe-hammerhead` here

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
FPR

**Pull request merged**
