### PR TITLE
Added typescript parser(closes #1642)

### LINKED ISSUE #1642: Add typescript support to the fixture parser

### PR DESCRIPTION
**Pull request by kirovboris**
/cc @AlexanderMoskovkin @helen-dikareva

### CODE REVIEW

**Comment by kirovboris** [comment]
@testcafe-build-bot \retest

**Comment by kirovboris** [comment]
@testcafe-build-bot \retest

**Comment by kirovboris** [comment]
@testcafe-build-bot \retest

**Comment by kirovboris** [comment]
@testcafe-build-bot \retest

**Comment by kirovboris** [comment]
@testcafe-build-bot \retest

**Comment by kirovboris** [comment]
@testcafe-build-bot \retest

**Comment by kirovboris** [comment]
@testcafe-build-bot \retest

**Comment by kirovboris** [comment]
@testcafe-build-bot \retest

**Comment by kirovboris** [comment]
@testcafe-build-bot \retest

**Comment by kirovboris** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
@kirovboris said me about parsing `.ts` files based on already parsed ast structures.
But may be we should add test for real `.ts` test, like [here ](https://github.com/DevExpress/testcafe/blob/master/test/functional/fixtures/api/typescript/smoke/testcafe-fixtures/callsite-test.ts)

**Comment by kirovboris** [comment]
FPR

**Comment by kirovboris** [comment]
ping @helen-dikareva

**Pull request merged**
